insert into Equipment_Type (type_id, type_name, description) values (1, 'Ray Defense Borad Spectrum SPF 30 sunscreen', 'Frozen vegan tacos filled with plant-based protein and spices.');
insert into Equipment_Type (type_id, type_name, description) values (2, 'Equetro', 'Savory sausage links seasoned with Italian spices.');
insert into Equipment_Type (type_id, type_name, description) values (3, 'zaleplon', 'Chic slingback sandals for a relaxed summer vibe.');
insert into Equipment_Type (type_id, type_name, description) values (4, 'Gemfibrozil', 'Roasted Brussels sprouts drizzled with balsamic glaze.');
insert into Equipment_Type (type_id, type_name, description) values (5, 'PROMETHAZINE DM', 'Tender chicken coated in a sweet and savory honey garlic sauce.');
insert into Equipment_Type (type_id, type_name, description) values (6, 'Penicillin V Potassium', 'Manual blender for smoothies and mixing ingredients on the go.');
insert into Equipment_Type (type_id, type_name, description) values (7, 'ATORVASTATIN CALCIUM', 'Complete station with supplies for kids'' art projects.');
insert into Equipment_Type (type_id, type_name, description) values (8, 'Analgesic', 'Classic chicken noodle soup with tender chicken and vegetables.');
insert into Equipment_Type (type_id, type_name, description) values (9, 'Utah Juniper', 'Adds extra comfort to your mattress for a better night''s sleep.');
insert into Equipment_Type (type_id, type_name, description) values (10, 'ACD', 'Compact air fryer for healthier cooking.');
insert into Equipment_Type (type_id, type_name, description) values (11, 'FeverALL Junior', 'Foldable reclining camping chair with cup holder.');
insert into Equipment_Type (type_id, type_name, description) values (12, 'Pleo Pef', 'Beginner-friendly acoustic guitar with natural finish.');
insert into Equipment_Type (type_id, type_name, description) values (13, 'Gentak', 'A seasoning blend of garlic and herbs to enhance any dish.');
insert into Equipment_Type (type_id, type_name, description) values (14, 'Liquid Oxygen', 'Cordless electric knife for effortless slicing.');
insert into Equipment_Type (type_id, type_name, description) values (15, 'RoC Multi Correxion', 'Plant-based mix for a rich chocolate cake.');
insert into Equipment_Type (type_id, type_name, description) values (16, 'Aristospan', 'Nutty flavored chia seeds, packed with nutrients.');
insert into Equipment_Type (type_id, type_name, description) values (17, 'cephalexin', 'Fluffy couscous that cooks in just minutes, perfect as a side.');
insert into Equipment_Type (type_id, type_name, description) values (18, 'LEVOPHED', 'Easy-to-make pancake mix with pumpkin spice flavor.');
insert into Equipment_Type (type_id, type_name, description) values (19, 'amlodipine besylate', 'Instant ramen cups with flavor-packed broth.');
insert into Equipment_Type (type_id, type_name, description) values (20, 'RESTORIL', 'Breathable linen trousers perfect for hot weather.');
insert into Equipment_Type (type_id, type_name, description) values (21, 'Western White Pine', 'High-density, non-slip yoga mat for stability and comfort.');
insert into Equipment_Type (type_id, type_name, description) values (22, 'Standardized Grass Pollen, Bluegrass, Kentucky (June)', 'Tofu stir-fried with fresh vegetables in teriyaki sauce.');
insert into Equipment_Type (type_id, type_name, description) values (23, 'Chap-et', 'Creamy yogurt made from coconut milk, dairy-free and delicious.');
insert into Equipment_Type (type_id, type_name, description) values (24, 'divalproex sodium', 'Compact camp stove for outdoor cooking.');
insert into Equipment_Type (type_id, type_name, description) values (25, 'Kerydin', 'Assorted nail polish set for vibrant nails.');
insert into Equipment_Type (type_id, type_name, description) values (26, 'Head and Shoulders 2in1', 'Light and crispy rice cakes, a perfect low-calorie snack.');
insert into Equipment_Type (type_id, type_name, description) values (27, 'oxandrolone', 'Crunchy granola mixed with maple syrup and cinnamon, perfect for breakfast or snacks.');
insert into Equipment_Type (type_id, type_name, description) values (28, 'Carbamazepine', 'Compact food processor for quick meal prep.');
insert into Equipment_Type (type_id, type_name, description) values (29, 'Secret Brazil Clear', 'Classic wooden train set for imaginative play.');
insert into Equipment_Type (type_id, type_name, description) values (30, 'Dexamethasone Sodium Phosphate', 'Chic suede ankle booties, perfect for dressing up or down.');
insert into Equipment_Type (type_id, type_name, description) values (31, 'Boscia BB SPF 27 PA', 'Mix for homemade cornbread, just add water and bake for a delicious side.');
insert into Equipment_Type (type_id, type_name, description) values (32, 'Fosphenytoin', 'Delicious pasta shells filled with spinach and cheese');
insert into Equipment_Type (type_id, type_name, description) values (33, 'Cephalexin', 'A sweet and spicy salsa made with mangoes and a hint of chili, great with chips or grilled chicken.');
insert into Equipment_Type (type_id, type_name, description) values (34, 'Naproxen', 'Planter with self-watering feature for easy plant care.');
insert into Equipment_Type (type_id, type_name, description) values (35, 'Tinidazole', 'Thin, flat pasta perfect for various sauces.');
insert into Equipment_Type (type_id, type_name, description) values (36, 'leader nite time', 'Classic marinara sauce for pasta, pizza, or dipping.');
insert into Equipment_Type (type_id, type_name, description) values (37, 'Arnica Aurum 6/10', 'Versatile puff pastry for pies and pastries.');
insert into Equipment_Type (type_id, type_name, description) values (38, 'DELFLEX', 'Sweet and chewy dried mango slices, perfect for snacking.');
insert into Equipment_Type (type_id, type_name, description) values (39, 'Ropinirole Hydrochloride', 'Compact blender that comes with travel cups for smoothies.');
insert into Equipment_Type (type_id, type_name, description) values (40, 'Expectorant', 'Ultrasonic essential oil diffuser with LED lights.');
insert into Equipment_Type (type_id, type_name, description) values (41, 'Ampicillin', 'Creamy Greek yogurt infused with raspberry and vanilla flavors.');
insert into Equipment_Type (type_id, type_name, description) values (42, 'Type 7 Stress Anxiety Regular', 'Collapsible travel bowl for pets on the go.');
insert into Equipment_Type (type_id, type_name, description) values (43, 'Ibuprofen', 'Monitor and interact with your pet remotely with this camera.');
insert into Equipment_Type (type_id, type_name, description) values (44, 'Leader Nite Time', 'Warm oatmeal flavored with apple and cinnamon.');
insert into Equipment_Type (type_id, type_name, description) values (45, 'Aurum Olibanum Myrrha', 'Blend of cheddar and mozzarella cheese, great for recipes.');
insert into Equipment_Type (type_id, type_name, description) values (46, 'Simvastatin', 'Compact pocket tool with various built-in functions.');
insert into Equipment_Type (type_id, type_name, description) values (47, 'FiberTab', 'Magical lens kit for kids to explore the outdoors.');
insert into Equipment_Type (type_id, type_name, description) values (48, 'OXYCODONE HYDROCHLORIDE', 'Crispy baked radish chips, a healthy snack alternative.');
insert into Equipment_Type (type_id, type_name, description) values (49, 'temazepam', 'Artichoke hearts marinated in herbs and oil.');
insert into Equipment_Type (type_id, type_name, description) values (50, 'Hydrochlorothiazide', 'Eco-friendly yoga mat made from sustainable materials.');
insert into Equipment_Type (type_id, type_name, description) values (51, 'AugmentinXR', 'Everything you need to make your own candles.');
insert into Equipment_Type (type_id, type_name, description) values (52, 'Tramadol Hydrochloride', 'Tangy goat cheese infused with herbs, perfect for snacking.');
insert into Equipment_Type (type_id, type_name, description) values (53, 'NORTRIPTYLINE HYDROCHLORIDE', 'Sweet peach halves packed in juice, great for desserts.');
insert into Equipment_Type (type_id, type_name, description) values (54, 'Dermisil', 'Comfortable gaming chair for long hours of play.');
insert into Equipment_Type (type_id, type_name, description) values (55, 'Bupropion Hydrochloride', 'Savory oatmeal ready to eat, great for breakfast or a snack.');
insert into Equipment_Type (type_id, type_name, description) values (56, 'Prazosin Hydrochloride', 'Space-saving solution to store shoes and keep them organized.');
insert into Equipment_Type (type_id, type_name, description) values (57, 'RANITIDINE', 'Layered Greek yogurt with granola and mixed berries, ready to enjoy.');
insert into Equipment_Type (type_id, type_name, description) values (58, 'Aspirin', 'Soft and chewy bar packed with protein and cinnamon flavors.');
insert into Equipment_Type (type_id, type_name, description) values (59, 'Molds, Rusts and Smuts, Hormodendrum cladosporioides', 'Connect your phone to the car''s audio system via Bluetooth.');
insert into Equipment_Type (type_id, type_name, description) values (60, 'Escitalopram', 'Storage organizer for art supplies and tools.');
insert into Equipment_Type (type_id, type_name, description) values (61, 'SPAI-SONS', 'Creamy mashed sweet potatoes, ready to heat and serve.');
insert into Equipment_Type (type_id, type_name, description) values (62, 'Sulfamethoxazole and Trimethoprim', 'Creamy chia pudding made with coconut milk and topped with mango.');
insert into Equipment_Type (type_id, type_name, description) values (63, 'Rescue Remedy', 'Complete set of gardening tools for all your needs.');
insert into Equipment_Type (type_id, type_name, description) values (64, 'Kirkland Signature Minoxidil', 'Water bottle designed to infuse flavors from fruits.');
insert into Equipment_Type (type_id, type_name, description) values (65, 'Equate Childrens Pain and Fever', 'Toy drone that flies with gestures and is easy to control.');
insert into Equipment_Type (type_id, type_name, description) values (66, 'Medrox', 'Stream HD video wirelessly from devices to TV.');
insert into Equipment_Type (type_id, type_name, description) values (67, 'Metoclopramide', 'Corn on the cob seasoned with chili and lime for a spicy kick.');
insert into Equipment_Type (type_id, type_name, description) values (68, 'DR. RECKEWEG R43 Herbamine', 'A creamy pumpkin soup with a blend of warm spices, ready to heat and serve.');
insert into Equipment_Type (type_id, type_name, description) values (69, 'Caverject Impulse', 'Blender for smoothies with a portable cup.');
insert into Equipment_Type (type_id, type_name, description) values (70, 'Head and Shoulders Dual Sachets', 'Crispy sweet potato fries, a delicious side dish.');
insert into Equipment_Type (type_id, type_name, description) values (71, 'buprenorphine hydrochloride', 'Freshly baked bagels, perfect for breakfast or snacks.');
insert into Equipment_Type (type_id, type_name, description) values (72, 'OxyContin', 'Light and crunchy rice cakes made from organic brown rice.');
insert into Equipment_Type (type_id, type_name, description) values (73, 'Nitrogen', 'Modern desk lamp that features a built-in USB charging port.');
insert into Equipment_Type (type_id, type_name, description) values (74, 'Fluoxetine', 'Elegant glass teapot for brewing loose tea.');
insert into Equipment_Type (type_id, type_name, description) values (75, 'Oral Analgesic', 'Essential ingredient for baking and cooking.');
insert into Equipment_Type (type_id, type_name, description) values (76, 'Furosemide', 'Modern LED table lamp with touch control.');
insert into Equipment_Type (type_id, type_name, description) values (77, 'COREG', 'Battery-operated air purifier for small spaces.');
insert into Equipment_Type (type_id, type_name, description) values (78, 'Oxygen', 'Beginner-friendly acoustic guitar with natural finish.');
insert into Equipment_Type (type_id, type_name, description) values (79, 'Pitocin', 'Special attachment for vacuum cleaners to remove pet hair easily.');
insert into Equipment_Type (type_id, type_name, description) values (80, 'Lisinopril and hydrochlorothiazide', 'Compact hair dryer with multiple heat settings.');
insert into Equipment_Type (type_id, type_name, description) values (81, 'Fluoxetine', 'Freshly baked artisan bread with a crisp crust and soft center.');
insert into Equipment_Type (type_id, type_name, description) values (82, 'Tums', 'Timeless black trousers for a smart and sophisticated look.');
insert into Equipment_Type (type_id, type_name, description) values (83, 'TERCONAZOLE', 'Eco-friendly power bank that charges via sunlight.');
insert into Equipment_Type (type_id, type_name, description) values (84, 'MEDI-PATCH', 'Savory bacon jerky coated with maple flavoring.');
insert into Equipment_Type (type_id, type_name, description) values (85, 'Amoxicillin', 'Creamy risotto made with mushrooms and herbs, perfect as a side dish or main course.');
insert into Equipment_Type (type_id, type_name, description) values (86, 'Mycophenolate Mofetil', 'Crunchy granola with oats, nuts, and honey.');
insert into Equipment_Type (type_id, type_name, description) values (87, 'Nu Skin Tri-Phasic White System', 'Instant pressure cooker with multiple cooking settings.');
insert into Equipment_Type (type_id, type_name, description) values (88, 'Losortan Potassium', 'A flavorful barbecue sauce with a sweet and spicy kick.');
insert into Equipment_Type (type_id, type_name, description) values (89, 'Abstral', 'Sweet pineapple chunks in syrup.');
insert into Equipment_Type (type_id, type_name, description) values (90, 'Estradiol / Norethindrone Acetate', 'Eco-friendly utensil set made from natural wood.');
insert into Equipment_Type (type_id, type_name, description) values (91, 'METHOTREXATE', 'Compact and stylish indoor/outdoor fire pit for ambiance.');
insert into Equipment_Type (type_id, type_name, description) values (92, 'ZOLPIDEM TARTRATE', 'Fun gardening tools designed specifically for kids.');
insert into Equipment_Type (type_id, type_name, description) values (93, 'IVA ANNUA VAR ANNUA POLLEN', 'Frozen shrimp seasoned with chili and lime, perfect for quick dinners.');
insert into Equipment_Type (type_id, type_name, description) values (94, 'Escitalopram', 'Double-sided art easel for painting and drawing.');
insert into Equipment_Type (type_id, type_name, description) values (95, 'Bellagio Sunscreen SPF 15', 'Coffee blend infused with pumpkin spice, perfect for fall.');
insert into Equipment_Type (type_id, type_name, description) values (96, 'Fusarium', 'Sweet and savory sauce for marinating and glazing meats or vegetables.');
insert into Equipment_Type (type_id, type_name, description) values (97, 'Lamb Quarters', 'Powerful electric pressure washer for deep cleaning.');
insert into Equipment_Type (type_id, type_name, description) values (98, 'CLARINS Skin Illusion SPF 10 Natural Radiance Foundation Tint 110', 'Lightweight and portable folding table for camping or picnics.');
insert into Equipment_Type (type_id, type_name, description) values (99, 'diphenhydramine hydrochloride', 'Creamy mashed sweet potatoes, ready to heat and serve.');
insert into Equipment_Type (type_id, type_name, description) values (100, 'Genuine Hydrocortisone', 'A warm and sustainable wool scarf for chilly days.');
insert into Equipment_Type (type_id, type_name, description) values (101, 'Escitalopram', 'A variety pack of classic, roasted red pepper, and garlic hummus.');
insert into Equipment_Type (type_id, type_name, description) values (102, 'QC Cold and Hot Pain Relief', 'Stay warm with this stylish knit beanie in various colors.');
insert into Equipment_Type (type_id, type_name, description) values (103, 'Lovenox', 'Electric foot massager for relaxation and relief.');
insert into Equipment_Type (type_id, type_name, description) values (104, 'Minivelle', 'Passive noise reduction headphones for focus.');
insert into Equipment_Type (type_id, type_name, description) values (105, 'Panama Jack', 'Comfortable headset with surround sound for immersive gaming.');
insert into Equipment_Type (type_id, type_name, description) values (106, 'Brightening Hand Broad Spectrum SPF 20', 'Gourmet potato skins loaded with cheddar cheese and bacon.');
insert into Equipment_Type (type_id, type_name, description) values (107, 'OXYGEN', 'Eco-friendly coffee filter for brewing.');
insert into Equipment_Type (type_id, type_name, description) values (108, 'Halls', 'Flexible molds perfect for baking cakes and pastries.');
insert into Equipment_Type (type_id, type_name, description) values (109, 'SUPER ORIGIN COTTON FINISH FOUNDATION', 'Fun lunchbox for kids with a sturdy design.');
insert into Equipment_Type (type_id, type_name, description) values (110, 'mally Face Defender Foundation BB', 'Fun light that creates a disco atmosphere for parties.');
insert into Equipment_Type (type_id, type_name, description) values (111, 'Cefprozil', 'A flavorful sauce made with coconut milk and spices.');
insert into Equipment_Type (type_id, type_name, description) values (112, 'Angeliq', 'Eco-friendly sealer for protecting concrete surfaces.');
insert into Equipment_Type (type_id, type_name, description) values (113, 'Finasteride', 'Durable and shatterproof silicone glasses for outdoor use.');
insert into Equipment_Type (type_id, type_name, description) values (114, 'LBEL', 'Small toolkit with essentials for home repairs.');
insert into Equipment_Type (type_id, type_name, description) values (115, 'Oxcarbazepine', 'Creamy ricotta cheese, great for cooking or making desserts.');
insert into Equipment_Type (type_id, type_name, description) values (116, 'Terocin', 'Layers of pasta, veggies, and cheese baked to perfection.');
insert into Equipment_Type (type_id, type_name, description) values (117, 'Ranexa', 'Soft and pillowy gnocchi made from cauliflower, perfect with sauce.');
insert into Equipment_Type (type_id, type_name, description) values (118, 'DR. RECKEWEG R51 Thyreosan', 'A sweet and tart jam, perfect on toast or in desserts.');
insert into Equipment_Type (type_id, type_name, description) values (119, 'Cetirizine Hydrochloride', 'Compact Bluetooth speaker with rich sound quality.');
insert into Equipment_Type (type_id, type_name, description) values (120, 'Mirtazapine', 'Fresh button mushrooms, great for cooking.');
insert into Equipment_Type (type_id, type_name, description) values (121, 'DYSMENORRHEA FATIGUE', 'Sweet and tangy jam made from natural apricots.');
insert into Equipment_Type (type_id, type_name, description) values (122, 'Dicyclomine', 'Mix for homemade cornbread, just add water and bake for a delicious side.');
insert into Equipment_Type (type_id, type_name, description) values (123, 'Ziprasidone Hydrochloride', 'A whole free-range chicken, ready for roasting.');
insert into Equipment_Type (type_id, type_name, description) values (124, 'Budpak Baby', 'A flavorful barbecue sauce with a sweet and spicy kick.');
insert into Equipment_Type (type_id, type_name, description) values (125, 'Dust, House Mixture', 'Everything you need to make your own candles.');
insert into Equipment_Type (type_id, type_name, description) values (126, 'Veratrum Chamomilla', 'All-in-one meal kit including pasta, meatballs, and sauce for a quick dinner.');
insert into Equipment_Type (type_id, type_name, description) values (127, 'Amoxicillin and Clavulanate Potassium', 'Nutty flavored chia seeds, packed with nutrients.');
insert into Equipment_Type (type_id, type_name, description) values (128, 'Warfarin Sodium', 'A nutritious salad with kale, quinoa, and a zesty lemon dressing.');
insert into Equipment_Type (type_id, type_name, description) values (129, 'Horse Hair', 'Storage solutions for keeping your car tidy and organized.');
insert into Equipment_Type (type_id, type_name, description) values (130, 'Simvastatin', 'Fun tabletop air hockey for home or office.');
insert into Equipment_Type (type_id, type_name, description) values (131, 'Natures Antibac Orange Vanilla', 'Manual pasta maker for creating fresh pasta at home.');
insert into Equipment_Type (type_id, type_name, description) values (132, 'Tegretol', 'Electric foot massager with heat settings.');
insert into Equipment_Type (type_id, type_name, description) values (133, 'Cotton Linters', 'Complete kit to make your own flavored lip balms at home.');
insert into Equipment_Type (type_id, type_name, description) values (134, 'TOPCARE MAXIMUM STRENGTH URINARY PAIN RELIEF', 'Spicy salsa made with black beans and tomatoes.');
insert into Equipment_Type (type_id, type_name, description) values (135, 'Trokendi XR', 'Bluetooth scale that tracks body composition through an app.');
insert into Equipment_Type (type_id, type_name, description) values (136, 'Original Redness Reliever', 'A versatile black dress that can be styled for any occasion.');
insert into Equipment_Type (type_id, type_name, description) values (137, 'Moisture Therapy', 'Baked kale chips seasoned for a healthy, crunchy snack.');
insert into Equipment_Type (type_id, type_name, description) values (138, 'Western Wheatgrass Pollen', 'Soft throw blanket for cozy home decor.');
insert into Equipment_Type (type_id, type_name, description) values (139, 'Cefaclor', 'A delicious chicken dish featuring honey and sesame flavors.');
insert into Equipment_Type (type_id, type_name, description) values (140, 'CYZONE', 'Complete tattoo kit for beginners and professionals.');
insert into Equipment_Type (type_id, type_name, description) values (141, 'Alpha-Caine', 'Frozen cauliflower bites coated in spicy buffalo sauce, ready to bake and enjoy as an appetizer.');
insert into Equipment_Type (type_id, type_name, description) values (142, 'Coast Maple', 'Frozen mini meatballs that are great as a snack or in pasta dishes.');
insert into Equipment_Type (type_id, type_name, description) values (143, 'Losartan Potassium and Hydrochlorothiazide', 'All-in-one mix for easy homemade cheeseburgers, just add ground beef.');
insert into Equipment_Type (type_id, type_name, description) values (144, 'DR. IASO UV TOTAL BASE SPF 46 PA', 'Zesty seasoning great for tacos and grilling.');
insert into Equipment_Type (type_id, type_name, description) values (145, 'LIMA BEAN', 'Non-stick and reusable mats for easy baking.');
insert into Equipment_Type (type_id, type_name, description) values (146, 'Dove', 'A hearty salad with grains, dried fruits, and nuts.');
insert into Equipment_Type (type_id, type_name, description) values (147, 'Glumetza', 'Challenging puzzle game set for family entertainment.');
insert into Equipment_Type (type_id, type_name, description) values (148, 'up and up', 'Compact hand mixer for easy baking.');
insert into Equipment_Type (type_id, type_name, description) values (149, 'Amoxicillin', 'Portable water bottle for pets when traveling.');
insert into Equipment_Type (type_id, type_name, description) values (150, 'Naproxen', 'Fresh Brussels sprouts, great for roasting or steaming.');
insert into Equipment_Type (type_id, type_name, description) values (151, 'METFORMIN HYDROCHLORIDE', 'Collapsible travel bowl for pets on the go.');
insert into Equipment_Type (type_id, type_name, description) values (152, 'GOOD SENSE IBUPROFEN', 'Dairy-free cheese alternative for your favorite dishes.');
insert into Equipment_Type (type_id, type_name, description) values (153, 'Baclofen', 'A zesty marinade made with lemon juice and garlic, ideal for chicken or fish.');
insert into Equipment_Type (type_id, type_name, description) values (154, 'Anti-Itch', 'Eco-friendly trash bags that break down naturally.');
insert into Equipment_Type (type_id, type_name, description) values (155, 'Promethazine Hydrochloride', 'Microwaveable heat pad for soothing muscle aches.');
insert into Equipment_Type (type_id, type_name, description) values (156, 'Klor-Con M', 'Rich sauce for desserts and ice cream.');
insert into Equipment_Type (type_id, type_name, description) values (157, 'Publix Burn Relief', 'A hearty salad with grains, dried fruits, and nuts.');
insert into Equipment_Type (type_id, type_name, description) values (158, 'Isopropyl alcohol', 'Healthy pizza crust made from cauliflower');
insert into Equipment_Type (type_id, type_name, description) values (159, 'Naproxen', 'Comprehensive emergency kit for roadside assistance.');
insert into Equipment_Type (type_id, type_name, description) values (160, 'KleerSight', 'A mix of brined Mediterranean olives for snacking.');
insert into Equipment_Type (type_id, type_name, description) values (161, 'childrens mucus relief multi symptom cold', 'Eco-friendly reusable bags for snacks.');
insert into Equipment_Type (type_id, type_name, description) values (162, 'LBEL MAXIMUM COMFORT AND LONG-LASTING FOUNDATION SPF 10', 'Fresh salad with pears, gorgonzola cheese, and nuts, perfect for lunch.');
insert into Equipment_Type (type_id, type_name, description) values (163, 'Metolazone', 'A sweet and tangy vinaigrette dressing for salads.');
insert into Equipment_Type (type_id, type_name, description) values (164, 'ANASPAZ', 'Spicy salsa made with fresh ingredients.');
insert into Equipment_Type (type_id, type_name, description) values (165, 'Latanoprost', 'Freshly roasted coffee beans with rich flavor.');
insert into Equipment_Type (type_id, type_name, description) values (166, 'Sweet Potato', 'Soft and delicious garlic-infused flatbread, perfect for dipping.');
insert into Equipment_Type (type_id, type_name, description) values (167, 'Snore Soothe', 'Portable ring light that enhances your photos with perfect lighting.');
insert into Equipment_Type (type_id, type_name, description) values (168, 'PCXX ONE MINTE GEL LUSCIOUS LIME', 'Complete kit for starting your own organic garden.');
insert into Equipment_Type (type_id, type_name, description) values (169, 'Childrens Pain Relief', 'Compact organizer for cosmetics during travel.');
insert into Equipment_Type (type_id, type_name, description) values (170, 'Loratadine', 'Creamy Greek yogurt infused with raspberry and vanilla flavors.');
insert into Equipment_Type (type_id, type_name, description) values (171, 'SNAIL THERAPY 70 EYE', 'Sweet and juicy strawberries, perfect for desserts.');
insert into Equipment_Type (type_id, type_name, description) values (172, 'simply right nicotine', 'Complete set for garden care with a handy carrying bag.');
insert into Equipment_Type (type_id, type_name, description) values (173, 'Diurex', 'Fresh Brussels sprouts, great for roasting or steaming.');
insert into Equipment_Type (type_id, type_name, description) values (174, 'Daytime Nighttime', 'Stream HD video wirelessly to your TV.');
insert into Equipment_Type (type_id, type_name, description) values (175, 'ADVATE', 'Passive noise reduction headphones for focus.');
insert into Equipment_Type (type_id, type_name, description) values (176, 'Quetiapine fumarate', 'Set of ceramic knives for precision slicing.');
insert into Equipment_Type (type_id, type_name, description) values (177, 'Premier Value Adult Glycerin', 'A savory marinade for meats, perfect for grilling.');
insert into Equipment_Type (type_id, type_name, description) values (178, 'Everyday Clean', 'Frozen green peas, a great addition to meals.');
insert into Equipment_Type (type_id, type_name, description) values (179, 'Pollens - Weeds, Dock/Sorrel Mix', 'A mix of fresh vegetables for quick stir-fries.');
insert into Equipment_Type (type_id, type_name, description) values (180, 'Methocarbamol', 'Love-themed molds for creating desserts and treats.');
insert into Equipment_Type (type_id, type_name, description) values (181, 'Sonata', 'Rechargeable screwdriver with multiple bits for DIY projects.');
insert into Equipment_Type (type_id, type_name, description) values (182, 'Simcor', 'Savory hash made with sweet potatoes and kale, a perfect side dish.');
insert into Equipment_Type (type_id, type_name, description) values (183, 'Citrus Urtica comp. Special Order', 'A colorful printed maxi skirt for a bohemian look.');
insert into Equipment_Type (type_id, type_name, description) values (184, 'Metoprolol succinate', 'Eco-friendly silicone bags for food storage and snacks.');
insert into Equipment_Type (type_id, type_name, description) values (185, 'Aspirin', 'Set of whisks in various sizes for cooking.');
insert into Equipment_Type (type_id, type_name, description) values (186, 'Prenaissance Plus', 'Color-changing smart LED bulbs compatible with Alexa.');
insert into Equipment_Type (type_id, type_name, description) values (187, 'No7 Beautiful Skin day Normal Dry Sunscreen Broad Spectrum SPF 15', 'A mix of brined Mediterranean olives for snacking.');
insert into Equipment_Type (type_id, type_name, description) values (188, 'DOXEPIN HYDROCHLORIDE', 'Portable projector with 1080p resolution for movies.');
insert into Equipment_Type (type_id, type_name, description) values (189, 'Terazosin Hydrochloride Anhydrous', 'Organic rolled oats, great for breakfast or baking.');
insert into Equipment_Type (type_id, type_name, description) values (190, 'Citalopram', 'Classic fit blue jeans with a slight stretch for comfort and durability.');
insert into Equipment_Type (type_id, type_name, description) values (191, 'Ziprasidone hydrochloride', 'Natural elderberry syrup to boost immunity.');
insert into Equipment_Type (type_id, type_name, description) values (192, 'Complexion Clear Acne Treatment Rejuvenating', 'A rich marinade perfect for meats and vegetables, infused with Italian herbs and balsamic vinegar.');
insert into Equipment_Type (type_id, type_name, description) values (193, 'APIS MELLIFICA', 'Savory sausage links with a hint of maple flavor.');
insert into Equipment_Type (type_id, type_name, description) values (194, 'Quality Choice Ibuprofen 200', 'A sleek leather wallet that combines style and functionality.');
insert into Equipment_Type (type_id, type_name, description) values (195, 'Metformin Hydrochloride', 'Crispy fries tossed in truffle oil and parmesan, a gourmet snack.');
insert into Equipment_Type (type_id, type_name, description) values (196, 'good neighbor pharmacy allergy', 'Multi-level cat tree for play and scratching.');
insert into Equipment_Type (type_id, type_name, description) values (197, 'Naproxen', 'Savory sausage with a blend of spices, perfect for pasta dishes.');
insert into Equipment_Type (type_id, type_name, description) values (198, 'Pantoprazole Sodium Delayed Release', 'Delicious recipes focusing on plant-based ingredients.');
insert into Equipment_Type (type_id, type_name, description) values (199, 'Petroleum', 'Thick and durable mat for workouts and yoga.');
insert into Equipment_Type (type_id, type_name, description) values (200, 'Omeprazole Delayed-Release', 'Freshly baked bagels, perfect for breakfast or snacks.');
insert into Equipment_Type (type_id, type_name, description) values (201, 'Minitran', 'Creamy cheese with a spicy kick, perfect for sandwiches.');
insert into Equipment_Type (type_id, type_name, description) values (202, 'Oxy Daily Defense Facial Cleanser', 'Comfortable mouse pad designed to reduce wrist strain.');
insert into Equipment_Type (type_id, type_name, description) values (203, 'Food - Plant Source, Melon, Cantaloupe Cucumis melo', 'Nutty-scented oil for stir-fry and marinades.');
insert into Equipment_Type (type_id, type_name, description) values (204, 'METOPROLOL SUCCINATE', 'Flavorful chicken wings marinated in a sweet teriyaki glaze.');
insert into Equipment_Type (type_id, type_name, description) values (205, 'Warfarin Sodium', 'Pasta alternative made from sweet potatoes, gluten-free and rich in flavor.');
insert into Equipment_Type (type_id, type_name, description) values (206, 'K-OK Kiddie Calmer', 'Heavy-duty scissors for crafting and office use.');
insert into Equipment_Type (type_id, type_name, description) values (207, 'Allopurinol', 'A casual striped long sleeve shirt that''s perfect for layering.');
insert into Equipment_Type (type_id, type_name, description) values (208, 'Cardio HP', 'Non-stick utensils for safe and easy cooking.');
insert into Equipment_Type (type_id, type_name, description) values (209, 'Escitalopram Oxalate', 'A flavorful blend of rice with tropical pineapple and coconut flavors.');
insert into Equipment_Type (type_id, type_name, description) values (210, 'Metronidazole', 'Floral and refreshing herbal tea, great hot or iced.');
insert into Equipment_Type (type_id, type_name, description) values (211, 'Western White Pine', 'Eco-friendly bamboo cutting boards in various sizes.');
insert into Equipment_Type (type_id, type_name, description) values (212, 'Pert Plus 2 in 1 Shampoo and Conditioner', 'Comfortable pet bed for small to medium-sized dogs.');
insert into Equipment_Type (type_id, type_name, description) values (213, 'Secret Invisible Solid', 'Eco-friendly silicone bags for food storage and snacks.');
insert into Equipment_Type (type_id, type_name, description) values (214, 'TOPICLEAR SKIN LIGHTENING', 'Crispy dill pickles that are perfect for snacking or sandwiches.');
insert into Equipment_Type (type_id, type_name, description) values (215, 'Leucovorin Calcium', 'A comforting soup filled with chicken and noodles in broth.');
insert into Equipment_Type (type_id, type_name, description) values (216, 'DESPEC', 'Delicious pretzel bites with a sweet honey mustard flavor, perfect for dipping.');
insert into Equipment_Type (type_id, type_name, description) values (217, 'Equate Childrens Pain and Fever', 'Creamy cheese with a spicy kick, perfect for sandwiches.');
insert into Equipment_Type (type_id, type_name, description) values (218, 'Quetiapine fumarate', 'Healthy salad made with quinoa, almonds, and mixed greens, perfect for a light meal.');
insert into Equipment_Type (type_id, type_name, description) values (219, 'allergy relief', 'Set of soothing scented candles for relaxation and ambiance.');
insert into Equipment_Type (type_id, type_name, description) values (220, 'HZ-Chord', 'Collapsible travel bowl for pets on the go.');
insert into Equipment_Type (type_id, type_name, description) values (221, 'Solar Defender SPF 30', 'A nutritious salad with kale, quinoa, and a zesty lemon dressing.');
insert into Equipment_Type (type_id, type_name, description) values (222, 'Cryptotox Combo', 'Organize your board games with this storage bin.');
insert into Equipment_Type (type_id, type_name, description) values (223, 'Skin Active', 'Healthy pizza crust made from cauliflower');
insert into Equipment_Type (type_id, type_name, description) values (224, 'Kadian', 'Comfortable gaming headset with surround sound.');
insert into Equipment_Type (type_id, type_name, description) values (225, 'Ondansetron', 'Rich sauce for desserts and ice cream.');
insert into Equipment_Type (type_id, type_name, description) values (226, 'Hydrochlorothiazide', 'A colorful printed maxi skirt for a bohemian look.');
insert into Equipment_Type (type_id, type_name, description) values (227, 'Pinceladas Para Hongos Navarro', 'A colorful variety of crunchy veggie chips for snacking.');
insert into Equipment_Type (type_id, type_name, description) values (228, 'Desmopressin Acetate', 'Instant ramen cups with flavor-packed broth.');
insert into Equipment_Type (type_id, type_name, description) values (229, 'Garnier Fructis Antidandruff', 'Sweet popcorn coated in a mixture of cinnamon and sugar.');
insert into Equipment_Type (type_id, type_name, description) values (230, 'Pramipexole Dihydrochloride', 'Comfortable trainers with mesh inserts for breathability.');
insert into Equipment_Type (type_id, type_name, description) values (231, 'Fosphenytoin Sodium', 'Eco-friendly charger with a built-in solar panel for outdoor use.');
insert into Equipment_Type (type_id, type_name, description) values (232, 'hemorrhoidal', 'Storage solutions for keeping your car tidy and organized.');
insert into Equipment_Type (type_id, type_name, description) values (233, 'Olanzapine', 'A creamy spread made with chocolate and hazelnuts, perfect for toast.');
insert into Equipment_Type (type_id, type_name, description) values (234, 'Atenolol', 'Creamy risotto infused with wild mushrooms.');
insert into Equipment_Type (type_id, type_name, description) values (235, '11 Thyroid Adrenal', 'Creamy peach-flavored yogurt with real fruit.');
insert into Equipment_Type (type_id, type_name, description) values (236, 'Lisinopril', 'Creamy and rich vanilla ice cream, a classic dessert.');
insert into Equipment_Type (type_id, type_name, description) values (237, 'Goodys Back and Body Pain', 'Easy-to-make falafel mix for a tasty vegetarian meal.');
insert into Equipment_Type (type_id, type_name, description) values (238, 'Standardized Grass Pollen, Sweet Vernal Grass', 'Gourmet potato skins loaded with cheddar cheese and bacon.');
insert into Equipment_Type (type_id, type_name, description) values (239, 'Oxygen', 'Concentrated tomato paste, great for sauces.');
insert into Equipment_Type (type_id, type_name, description) values (240, 'Klor-Con', 'Colorful bins to keep your space organized.');
insert into Equipment_Type (type_id, type_name, description) values (241, 'American Elm', 'Compact hose reel to keep your garden tidy.');
insert into Equipment_Type (type_id, type_name, description) values (242, 'Gelato APF', 'Organize travel documents, passport, and cards.');
insert into Equipment_Type (type_id, type_name, description) values (243, 'NABUMETONE', 'Traditional Korean fermented vegetables, packed with flavor.');
insert into Equipment_Type (type_id, type_name, description) values (244, 'Blistex', 'Activity workbook for early learning and fun.');
insert into Equipment_Type (type_id, type_name, description) values (245, 'Lymph Plus', 'Ready-to-bake garlic breadsticks, perfect with pasta dishes.');
insert into Equipment_Type (type_id, type_name, description) values (246, 'Baza Clear', 'Crunchy granola clusters, perfect for snacking or topping yogurt.');
insert into Equipment_Type (type_id, type_name, description) values (247, 'Pravastatin Sodium', 'True wireless earbuds with touch control.');
insert into Equipment_Type (type_id, type_name, description) values (248, 'Diabecline', 'A zero-calorie coconut oil spray for cooking and baking.');
insert into Equipment_Type (type_id, type_name, description) values (249, 'Mixture of Standardized and Non-Standardized Inland Grasses', 'Whole wheat wraps filled with spinach, feta, and herbs.');
insert into Equipment_Type (type_id, type_name, description) values (250, 'Womens Laxative', 'A frozen cheesy bake made with cauliflower, great as a side dish or a vegetarian meal.');
insert into Equipment_Type (type_id, type_name, description) values (251, 'Verapamil Hydrochloride', 'Stylish two-tone windbreaker, perfect for active days.');
insert into Equipment_Type (type_id, type_name, description) values (252, 'IQUIX', 'Stylish fruit basket for kitchen or dining room.');
insert into Equipment_Type (type_id, type_name, description) values (253, 'montelukast sodium', 'A lightweight tank dress, ideal for warm weather outings.');
insert into Equipment_Type (type_id, type_name, description) values (254, 'NOTUSS', 'Fresh and tart organic green apples, great for snacking or baking.');
insert into Equipment_Type (type_id, type_name, description) values (255, 'All Day Allergy', 'Float through the day in this beautiful floor-length skirt.');
insert into Equipment_Type (type_id, type_name, description) values (256, 'Clearasil Ultra Rapid Action', 'Eye-catching mini dress with sequins, ideal for party nights out.');
insert into Equipment_Type (type_id, type_name, description) values (257, 'Peptic Relief', 'A fragrant Indian spice blend for curries and stews.');
insert into Equipment_Type (type_id, type_name, description) values (258, 'Mixed Vespid Hymenoptera Venom Multidose', 'Fine granulated sugar for all your baking needs.');
insert into Equipment_Type (type_id, type_name, description) values (259, 'Pecan Pollen', 'Frozen shrimp seasoned with chili and lime, perfect for quick dinners.');
insert into Equipment_Type (type_id, type_name, description) values (260, 'Tamsulosin hydrochloride', 'Stylish fruit basket for kitchen or dining room.');
insert into Equipment_Type (type_id, type_name, description) values (261, 'Etodolac', 'Tempered glass screen protector for smartphones.');
insert into Equipment_Type (type_id, type_name, description) values (262, 'LBEL NATURAL FINISH MOISTURIZING FOUNDATION SPF 25', 'Everything you need to make delicious spicy tuna rolls at home.');
insert into Equipment_Type (type_id, type_name, description) values (263, 'TIAZAC', 'A delightful mix of chocolate, coconut, and almonds in a snack bar.');
insert into Equipment_Type (type_id, type_name, description) values (264, 'Benztropine Mesylate', 'Stylish faux leather leggings for a trendy outfit.');
insert into Equipment_Type (type_id, type_name, description) values (265, 'Nadolol', 'High-resolution camera for stunning photos.');
insert into Equipment_Type (type_id, type_name, description) values (266, 'GOJO E2 Foam Handwash with PCMX', 'A blend of dried herbs commonly used in Italian cooking.');
insert into Equipment_Type (type_id, type_name, description) values (267, 'all day relief', 'Refreshing coconut water, perfect for hydration.');
insert into Equipment_Type (type_id, type_name, description) values (268, 'Treatment Set TS343825', 'Freshly baked rustic bread, perfect for sandwiches or dipping in olive oil.');
insert into Equipment_Type (type_id, type_name, description) values (269, 'COUMADIN', 'Delicious turkey bacon, a healthier alternative.');
insert into Equipment_Type (type_id, type_name, description) values (270, 'Carvedilol', 'Portable folding camping chair with cup holder.');
insert into Equipment_Type (type_id, type_name, description) values (271, 'Neo-Synalar', 'Stay dry with these stylish waterproof rain boots.');
insert into Equipment_Type (type_id, type_name, description) values (272, 'Pramipexole dihydrochloride', 'Soft buns perfect for stuffing with your favorite hot dogs.');
insert into Equipment_Type (type_id, type_name, description) values (273, 'Ibuprofen', 'Nutritious protein bar with cherry and almond flavor, great for on-the-go.');
insert into Equipment_Type (type_id, type_name, description) values (274, 'PrismaSol', 'Tangy dressing perfect for salads and marinades, with sesame and ginger flavors.');
insert into Equipment_Type (type_id, type_name, description) values (275, 'ampicillin', 'Fluffy rice cooked with coconut milk for a tropical twist.');
insert into Equipment_Type (type_id, type_name, description) values (276, 'Midazolam', 'A mix of fresh vegetables for quick stir-fries.');
insert into Equipment_Type (type_id, type_name, description) values (277, 'ESIKA', 'Genuine leather wallet with multiple compartments.');
insert into Equipment_Type (type_id, type_name, description) values (278, 'Propranolol Hydrochloride', 'Creamy yogurt made from coconut milk, dairy-free and delicious.');
insert into Equipment_Type (type_id, type_name, description) values (279, 'LETTERS Lavender Hand Sanitizer', 'Comprehensive first aid kit for home and travel.');
insert into Equipment_Type (type_id, type_name, description) values (280, 'Lil Goats Zinc Oxide', 'Handheld vacuum cleaner for quick and easy cleaning.');
insert into Equipment_Type (type_id, type_name, description) values (281, 'leader nicotine', 'Roasted cashews coated in honey and sesame seeds for a sweet treat.');
insert into Equipment_Type (type_id, type_name, description) values (282, 'Allegra-D 24 Hour Allergy and Congestion', 'Healthy granola made with oats and honey.');
insert into Equipment_Type (type_id, type_name, description) values (283, 'PNEUMOVAX 23', 'Thin and crispy flatbreads, perfect for dips.');
insert into Equipment_Type (type_id, type_name, description) values (284, 'Modafinil', 'Educational tablet designed for preschool-age children.');
insert into Equipment_Type (type_id, type_name, description) values (285, 'Adidas 24H Anti Perspirant', 'High-performance mechanical keyboard with customizable RGB.');
insert into Equipment_Type (type_id, type_name, description) values (286, 'Prednisone', 'Ergonomic memory foam pillow for better sleep.');
insert into Equipment_Type (type_id, type_name, description) values (287, 'SENSAI TRIPLE TOUCH COMPACT TC03', 'Burr coffee grinder for fresh ground coffee.');
insert into Equipment_Type (type_id, type_name, description) values (288, 'Methotrexate Sodium', 'Automatic churner for making butter at home.');
insert into Equipment_Type (type_id, type_name, description) values (289, 'HAND SANITIZER', 'Compact vacuum designed specifically for cleaning vehicles.');
insert into Equipment_Type (type_id, type_name, description) values (290, 'Dextroamphetamine Saccharate, Amphetamine Aspartate, Dextroamphetamine Sulfate, and Amphetamine Sulfate', 'Wireless microphone for singing and performances.');
insert into Equipment_Type (type_id, type_name, description) values (291, 'Hasol Revitalizing', 'Complete sculpting tools for artists.');
insert into Equipment_Type (type_id, type_name, description) values (292, 'SmileGuard Just 4 Me', 'Comfortable slim fit chinos for a polished look.');
insert into Equipment_Type (type_id, type_name, description) values (293, 'CitraNatal Rx', 'Compact ice maker for creating ice at home or in offices.');
insert into Equipment_Type (type_id, type_name, description) values (294, 'SOLAR SENSE CLEAR ZINC SUNSCREEN FACE and BODY BROAD SPECTRUM SPF 50', 'Large inflatable pool for summer fun in your backyard.');
insert into Equipment_Type (type_id, type_name, description) values (295, 'Bebulin', 'A mix of fresh vegetables with a savory stir-fry sauce, ready to cook.');
insert into Equipment_Type (type_id, type_name, description) values (296, 'Candida albicans', 'Stylish two-tone windbreaker, perfect for active days.');
insert into Equipment_Type (type_id, type_name, description) values (297, 'Metoprolol Tartrate', 'Creamy yogurt made from almond milk, vegan-friendly.');
insert into Equipment_Type (type_id, type_name, description) values (298, 'CEPHALEXIN', 'Bright LED flashlight with adjustable beam.');
insert into Equipment_Type (type_id, type_name, description) values (299, 'Black Birch', 'A spicy glaze made with sriracha and honey, perfect for meats.');
insert into Equipment_Type (type_id, type_name, description) values (300, 'Cold-EEZE', 'Delicious dark chocolate with creamy nut butter inside.');
insert into Equipment_Type (type_id, type_name, description) values (301, 'Naproxen', 'Flavorful lentil soup, perfect for a quick meal.');
insert into Equipment_Type (type_id, type_name, description) values (302, 'Bio-S-Pres', 'Secure phone mount for your vehicle''s dashboard.');
insert into Equipment_Type (type_id, type_name, description) values (303, 'Island Blossom Antibacterial Foaming Hand Wash', 'Compact ice maker for creating ice at home or in offices.');
insert into Equipment_Type (type_id, type_name, description) values (304, 'Tonsilla compositum', 'Chic high-waisted skirt, perfect for professional or casual settings.');
insert into Equipment_Type (type_id, type_name, description) values (305, 'Bacteriostatic Water', 'Complete set designed for children to learn gardening.');
insert into Equipment_Type (type_id, type_name, description) values (306, 'American Crew Anti-Dandruff plus Sebum Control', 'Safe and vibrant crayons for children''s art projects.');
insert into Equipment_Type (type_id, type_name, description) values (307, 'lubricating plus', 'Roasted Brussels sprouts drizzled with balsamic glaze.');
insert into Equipment_Type (type_id, type_name, description) values (308, 'supernatural airbrushed canvas broad spectrum spf 15 sunscreen', 'A delicious tart filled with fresh raspberry filling.');
insert into Equipment_Type (type_id, type_name, description) values (309, 'Lamotrigine', 'Quick oatmeal packets infused with apple and cinnamon, perfect for breakfast.');
insert into Equipment_Type (type_id, type_name, description) values (310, 'Family wellness hemorrhoidal', 'Tangy goat cheese infused with herbs, perfect for snacking.');
insert into Equipment_Type (type_id, type_name, description) values (311, 'topcare fever reducer', 'Compact storage for your jewelry while traveling.');
insert into Equipment_Type (type_id, type_name, description) values (312, 'Low-Ogestrel', 'Stylish case with magnetic closure for smartphones.');
insert into Equipment_Type (type_id, type_name, description) values (313, 'Bio Reset/Jet Lag', 'Nutritious snack bar made with almond butter and protein.');
insert into Equipment_Type (type_id, type_name, description) values (314, 'Caraway Seed', 'Creamy cottage cheese, perfect for healthy snacking.');
insert into Equipment_Type (type_id, type_name, description) values (315, 'leader pain relief', 'Warm and stylish jacket for cold weather.');
insert into Equipment_Type (type_id, type_name, description) values (316, 'Dandruff', 'Indoor putting green for practicing your putting skills.');
insert into Equipment_Type (type_id, type_name, description) values (317, 'Scal-tonic intensive liquid', 'Hand-poured candles made of natural soy wax.');
insert into Equipment_Type (type_id, type_name, description) values (318, 'Fludrocortisone Acetate', 'Fresh and zesty salsa, perfect for nachos.');
insert into Equipment_Type (type_id, type_name, description) values (319, 'Acetazolamide', 'Delicious pasta shells filled with spinach and cheese');
insert into Equipment_Type (type_id, type_name, description) values (320, 'SHISEIDO THE MAKEUP FOUNDATION', 'Seasonal pumpkin ice cream, perfect for fall.');
insert into Equipment_Type (type_id, type_name, description) values (321, 'ESIKA', 'A complete meal kit containing breaded chicken breast, marinara sauce, and pasta, perfect for a quick dinner.');
insert into Equipment_Type (type_id, type_name, description) values (322, 'Rescue Remedy', 'Creamy ice cream with refreshing mint flavor and chocolate chips.');
insert into Equipment_Type (type_id, type_name, description) values (323, 'Doxepin Hydrochloride', 'Instant noodles with a spicy Thai sauce for quick meals.');
insert into Equipment_Type (type_id, type_name, description) values (324, 'METOPROLOL TARTRATE', 'Nutritious snack bar made with almond butter and protein.');
insert into Equipment_Type (type_id, type_name, description) values (325, 'Good Care Isopropyl Alcohol', 'Comfortable and warm leggings perfect for colder weather.');
insert into Equipment_Type (type_id, type_name, description) values (326, 'GABAPENTIN', 'Fresh organic cucumber perfect for salads or snacking.');
insert into Equipment_Type (type_id, type_name, description) values (327, 'Isopropyl Alcohol', 'Frozen salmon fillets marinated in teriyaki sauce, ready to grill or bake.');
insert into Equipment_Type (type_id, type_name, description) values (328, 'Sulwhasoo Lumitouch Foundation', 'Borosilicate glass water bottle with silicone sleeve.');
insert into Equipment_Type (type_id, type_name, description) values (329, 'Firebush/Burning Bush', 'Stability ball for Pilates and yoga workouts.');
insert into Equipment_Type (type_id, type_name, description) values (330, 'Buspirone Hydrochloride', 'Compact scooper for easy waste clean-up during walks.');
insert into Equipment_Type (type_id, type_name, description) values (331, 'NeoProfen', 'Pack of ultra-soft microfiber cloths for cleaning.');
insert into Equipment_Type (type_id, type_name, description) values (332, 'Atenolol', 'Creamy cheddar cheese slices, perfect for sandwiches and snacks.');
insert into Equipment_Type (type_id, type_name, description) values (333, 'Good Sense Aller Ease', 'Stability ball for Pilates and yoga workouts.');
insert into Equipment_Type (type_id, type_name, description) values (334, 'Lidocaine Hydrochloride', 'Crispy on the outside, tender on the inside, perfect for stir-fries or salads.');
insert into Equipment_Type (type_id, type_name, description) values (335, 'Hemorrhoidal', 'Crispy almonds coated with cinnamon and sugar for a sweet and crunchy snack.');
insert into Equipment_Type (type_id, type_name, description) values (336, 'Loratadine', 'Convenient feeder that adjusts to your pet''s height.');
insert into Equipment_Type (type_id, type_name, description) values (337, 'Protopic', 'Crispy breadsticks seasoned with herbs and garlic.');
insert into Equipment_Type (type_id, type_name, description) values (338, 'Lamotrigine', 'Thin, flat pasta perfect for various sauces.');
insert into Equipment_Type (type_id, type_name, description) values (339, 'Morphine Sulfate', 'Sturdy camera tripod for professional photography.');
insert into Equipment_Type (type_id, type_name, description) values (340, 'Ranitidine', 'Compact electric scooter for commuting and short trips.');
insert into Equipment_Type (type_id, type_name, description) values (341, 'Apiol', 'A trendy fanny pack, perfect for hands-free outings.');
insert into Equipment_Type (type_id, type_name, description) values (342, 'OIL CONTROLLING MAKEUP', 'A selection of different flavored hummus, great for snacking.');
insert into Equipment_Type (type_id, type_name, description) values (343, 'Butalbital, Acetaminophen, and Caffeine', 'Stylish markers for labeling your indoor garden plants.');
insert into Equipment_Type (type_id, type_name, description) values (344, 'BIOSOLIS Sun Milk UVA Sunscreen Face and Body Broad Spectrum SPF50 KIDS', 'Soft flannel shirt with a timeless plaid pattern, perfect for layering.');
insert into Equipment_Type (type_id, type_name, description) values (345, 'White Ash', 'Plain white rice, a staple for any meal.');
insert into Equipment_Type (type_id, type_name, description) values (346, 'CHILDRENS DIMETAPP MULTISYMPTOM COLD AND FLU', 'A refreshing drink mix that combines sweet raspberries and tart lemons, perfect for summer.');
insert into Equipment_Type (type_id, type_name, description) values (347, 'Orenitram', 'Non-toxic traps for catching household pests safely.');
insert into Equipment_Type (type_id, type_name, description) values (348, 'Lisinopril and Hydrochlorothiazide', 'Electric foot massager for relaxation and relief.');
insert into Equipment_Type (type_id, type_name, description) values (349, 'VALSARTAN', 'String lights for decorating holiday trees.');
insert into Equipment_Type (type_id, type_name, description) values (350, 'Rimmel London', 'Quick-boiling kettle for home and office use.');
insert into Equipment_Type (type_id, type_name, description) values (351, 'Omeprazole', 'Creamy yogurt made with coconut and cashews, dairy-free.');
insert into Equipment_Type (type_id, type_name, description) values (352, 'Lotensin HCT', 'High-performance mechanical keyboard with customizable RGB.');
insert into Equipment_Type (type_id, type_name, description) values (353, 'Sertraline Hydrochloride', 'A blend of spices that brings the taste of fall to your baked goods.');
insert into Equipment_Type (type_id, type_name, description) values (354, 'Wal Four', 'Sweet pineapple chunks in syrup.');
insert into Equipment_Type (type_id, type_name, description) values (355, 'Grama grass Pollen', 'Gluten-free pasta made from red lentils, packed with protein.');
insert into Equipment_Type (type_id, type_name, description) values (356, 'RoC Retinol Correxion Deep Wrinkle Daily Moisturizer', 'Lightweight water filter for outdoor adventures.');
insert into Equipment_Type (type_id, type_name, description) values (357, 'LBEL NATURAL FINISH MOISTURIZING FOUNDATION SPF 25', 'Pure and natural honey, great for sweetening.');
insert into Equipment_Type (type_id, type_name, description) values (358, 'Medrol', 'A warming blend of ginger and turmeric for lattes.');
insert into Equipment_Type (type_id, type_name, description) values (359, 'Levetiracetam', 'Freshly baked artisan bread, perfect for sandwiches or toasting.');
insert into Equipment_Type (type_id, type_name, description) values (360, 'Benzonatate', 'Rechargeable training collar for effective behavior training.');
insert into Equipment_Type (type_id, type_name, description) values (361, 'stila CC color correcting broad-spectrum SPF 20 02 LIGHT', 'A blend of dried fruits and nuts, great for snacking.');
insert into Equipment_Type (type_id, type_name, description) values (362, 'EPIVIR', 'Lightweight and portable swing hammock for relaxing outdoors.');
insert into Equipment_Type (type_id, type_name, description) values (363, 'Cranberry Cream Antibacterial Hand Wash', 'Handheld sprayer designed for washing pets easily.');
insert into Equipment_Type (type_id, type_name, description) values (364, 'Amoxicillin', 'Creamy pumpkin soup with spices');
insert into Equipment_Type (type_id, type_name, description) values (365, 'NERVE TONIC', 'Fresh, creamy avocados ideal for salads and guacamole.');
insert into Equipment_Type (type_id, type_name, description) values (366, 'Bites - Stings', 'Stylish wine rack to store and display bottles.');
insert into Equipment_Type (type_id, type_name, description) values (367, 'Pollens - Weeds, Careless/Pigweed Mix', 'STEM-based kit for kids featuring cool science experiments.');
insert into Equipment_Type (type_id, type_name, description) values (368, 'Severe Cold Multi-Symptom', 'Eco-friendly reusable bags for snacks.');
insert into Equipment_Type (type_id, type_name, description) values (369, 'Salmon', 'Powerful electric pressure washer for deep cleaning.');
insert into Equipment_Type (type_id, type_name, description) values (370, 'Triple Antibiotic HC', 'Personalized calendar with your favorite photos.');
insert into Equipment_Type (type_id, type_name, description) values (371, 'Benztropine Mesylate', 'Manual pasta maker for homemade pasta.');
insert into Equipment_Type (type_id, type_name, description) values (372, 'Dendracin Neurodendraxcin', 'A smoky barbecue sauce, ideal for grilling and dipping.');
insert into Equipment_Type (type_id, type_name, description) values (373, 'Quinapril Hydrochloride', 'Storage organizer for art supplies and tools.');
insert into Equipment_Type (type_id, type_name, description) values (374, 'Halls', 'Toy drone that flies with gestures and is easy to control.');
insert into Equipment_Type (type_id, type_name, description) values (375, 'Simvastatin', 'Tender sweet corn kernels, ready to eat or add to dishes.');
insert into Equipment_Type (type_id, type_name, description) values (376, 'UV LOCK ULTRA PACT SUN', 'Spicy sauce perfect for chicken wings and dipping.');
insert into Equipment_Type (type_id, type_name, description) values (377, 'Ondansetron', 'Spicy blue cheese with a hint of buffalo flavor.');
insert into Equipment_Type (type_id, type_name, description) values (378, 'HYZAAR', 'Digital scale to avoid overweight baggage fees.');
insert into Equipment_Type (type_id, type_name, description) values (379, '12 hour cough relief', 'Genuine leather wallet with multiple compartments.');
insert into Equipment_Type (type_id, type_name, description) values (380, 'Hielo Ardiente', 'Sweet, chewy dried apricots, great for snacking or baking.');
insert into Equipment_Type (type_id, type_name, description) values (381, 'Maracuja Miracle Foundation 12-Hour Foundation Broad Spectrum SPF 15 Sunscreen', 'Smart tracker to locate keys or other items via app.');
insert into Equipment_Type (type_id, type_name, description) values (382, 'Prandin', 'Crispy almonds coated with cinnamon and sugar for a sweet and crunchy snack.');
insert into Equipment_Type (type_id, type_name, description) values (383, 'Bacto Plus', 'Durable gloves with built-in claws for digging and planting.');
insert into Equipment_Type (type_id, type_name, description) values (384, 'SOLIDAGO CANADENSIS POLLEN', 'Soft blanket that provides warmth with adjustable settings.');
insert into Equipment_Type (type_id, type_name, description) values (385, 'Loxapine', 'Cook rice and steam vegetables simultaneously for healthy meals.');
insert into Equipment_Type (type_id, type_name, description) values (386, 'healthy accents nasal', 'Fluffy rice cooked with coconut milk for a tropical twist.');
insert into Equipment_Type (type_id, type_name, description) values (387, 'Lorazepam', 'Comfortable and breathable backpack for carrying small pets.');
insert into Equipment_Type (type_id, type_name, description) values (388, 'INSTANT Hand Sanitizer with Moisturizers All In One', 'Adjustable stand for smartphones and tablets.');
insert into Equipment_Type (type_id, type_name, description) values (389, 'Diltiazem Hydrochloride', 'Quick oatmeal packets infused with apple and cinnamon, perfect for breakfast.');
insert into Equipment_Type (type_id, type_name, description) values (390, 'Deb PureBac Foam Wash', 'Compact and stylish indoor/outdoor fire pit for ambiance.');
insert into Equipment_Type (type_id, type_name, description) values (391, 'Nymalize', 'Complete fondue set for chocolate and cheese parties.');
insert into Equipment_Type (type_id, type_name, description) values (392, 'Warfarin Sodium', 'Efficient juicer for fresh fruit and vegetable juices.');
insert into Equipment_Type (type_id, type_name, description) values (393, 'DIABETIC FOOT DEFENSE', 'Healthy granola made with oats and honey.');
insert into Equipment_Type (type_id, type_name, description) values (394, 'Polyethylene Glycol 3350', 'Eco-friendly sealer for protecting concrete surfaces.');
insert into Equipment_Type (type_id, type_name, description) values (395, 'Voltaren', 'Tangy sour cream, perfect for dips and toppings.');
insert into Equipment_Type (type_id, type_name, description) values (396, 'Burn Mist', 'All-in-one kit for making pasta salad easily.');
insert into Equipment_Type (type_id, type_name, description) values (397, 'Nitrogen', 'Fluffy couscous that cooks in just minutes, perfect as a side.');
insert into Equipment_Type (type_id, type_name, description) values (398, 'JANUVIA', 'Programmable digital thermostat for home heating.');
insert into Equipment_Type (type_id, type_name, description) values (399, 'Cialis', 'Crunchy pretzel nuggets filled with creamy peanut butter.');
insert into Equipment_Type (type_id, type_name, description) values (400, 'Effervescent Pain Relief Fast Relief', 'A refreshing sparkling beverage with a bold blood orange flavor.');
insert into Equipment_Type (type_id, type_name, description) values (401, 'Cefepime', 'Convenient carrier for transporting yoga mat.');
insert into Equipment_Type (type_id, type_name, description) values (402, 'Sulindac', 'Savory potato chips with a hint of maple sweetness and crispy bacon flavor.');
insert into Equipment_Type (type_id, type_name, description) values (403, 'Botanics Daily Hand Therapy Sunscreen SPF 10', 'Chic high-waisted skirt, perfect for professional or casual settings.');
insert into Equipment_Type (type_id, type_name, description) values (404, 'Thyropar', 'Citrusy lemons perfect for drinks and cooking.');
insert into Equipment_Type (type_id, type_name, description) values (405, 'miconazole 7', 'Microwaveable heating pad for muscle pain relief and relaxation.');
insert into Equipment_Type (type_id, type_name, description) values (406, 'Antibacterial Bar', 'Compact campfire for grilling and warmth during camping trips.');
insert into Equipment_Type (type_id, type_name, description) values (407, 'Bicalutamide', 'Creamy dessert made with rice and cinnamon.');
insert into Equipment_Type (type_id, type_name, description) values (408, 'Parsol Suncare SPF 29', 'Indoor gardening kit with herbs and pots.');
insert into Equipment_Type (type_id, type_name, description) values (409, 'Benztropine Mesylate', 'Safety collar with flashing lights for pets during night walks.');
insert into Equipment_Type (type_id, type_name, description) values (410, 'CELEBREX', 'Light and crispy chips made from quinoa, ideal for dipping.');
insert into Equipment_Type (type_id, type_name, description) values (411, 'Loxapine', 'A warm and sustainable wool scarf for chilly days.');
insert into Equipment_Type (type_id, type_name, description) values (412, 'Stings, Bites, Swellings', 'Stylish stand to hold your recipes while cooking.');
insert into Equipment_Type (type_id, type_name, description) values (413, 'venlafaxine hydrochloride', 'Lightweight and durable tent for camping trips.');
insert into Equipment_Type (type_id, type_name, description) values (414, 'PERTZYE', 'Ready-to-eat chicken bowl with teriyaki sauce and rice.');
insert into Equipment_Type (type_id, type_name, description) values (415, 'ACETADOTE', 'Energy-efficient LED bulbs that can be controlled via smartphone.');
insert into Equipment_Type (type_id, type_name, description) values (416, 'lubricating plus eye', 'Protective case for wireless earbuds.');
insert into Equipment_Type (type_id, type_name, description) values (417, 'dg health naproxen sodium', 'Crunchy granola with maple flavor and almond pieces for breakfast.');
insert into Equipment_Type (type_id, type_name, description) values (418, 'Quetiapine fumarate', 'Magical lens kit for kids to explore the outdoors.');
insert into Equipment_Type (type_id, type_name, description) values (419, 'Viscumforce', 'Creamy yogurt made from almond milk, vegan-friendly.');
insert into Equipment_Type (type_id, type_name, description) values (420, 'Geum Gentian 1 Special Order', 'Cute fairy figurines to decorate your garden or potted plants.');
insert into Equipment_Type (type_id, type_name, description) values (421, 'LOVASTATIN', 'Homemade ice cream maker for delicious desserts.');
insert into Equipment_Type (type_id, type_name, description) values (422, 'Diazepam', 'Sharp tailored blazer perfect for office wear and professional events.');
insert into Equipment_Type (type_id, type_name, description) values (423, 'HZ-Chord', 'Healthy pizza crust made from cauliflower');
insert into Equipment_Type (type_id, type_name, description) values (424, 'Evtox', 'Nutritious protein bars for on-the-go snacking.');
insert into Equipment_Type (type_id, type_name, description) values (425, 'Furosemide', 'A variety pack of classic, roasted red pepper, and garlic hummus.');
insert into Equipment_Type (type_id, type_name, description) values (426, 'CAPTOPRIL', 'Smooth and creamy, ideal for spreads or baking.');
insert into Equipment_Type (type_id, type_name, description) values (427, 'AMITRIPTYLINE HYDROCHLORIDE', 'Wild-caught salmon filets, perfect for grilling or baking.');
insert into Equipment_Type (type_id, type_name, description) values (428, 'Triple Antibiotic HC', 'Comprehensive camera and alert system for home security.');
insert into Equipment_Type (type_id, type_name, description) values (429, 'Buspirone Hydrochloride', 'Handheld vacuum cleaner for quick and easy cleaning.');
insert into Equipment_Type (type_id, type_name, description) values (430, 'Dandruff', 'Soft and cozy slippers for indoor wear.');
insert into Equipment_Type (type_id, type_name, description) values (431, 'Doxepin Hydrochloride', 'Lightweight cover-up perfect for the beach, with a breezy design.');
insert into Equipment_Type (type_id, type_name, description) values (432, 'Anti-acne', 'Crisp and delicious organic apples.');
insert into Equipment_Type (type_id, type_name, description) values (433, 'SUPER AQUA MAX WHITE C EYE BRIGHTENER', 'A sweet and spicy glaze that''s perfect for grilling or marinades.');
insert into Equipment_Type (type_id, type_name, description) values (434, 'DG Health Cold and Flu Relief', 'Fresh thyme, perfect for seasoning dishes.');
insert into Equipment_Type (type_id, type_name, description) values (435, 'Venus White', 'Automatic watering devices for potted plants.');
insert into Equipment_Type (type_id, type_name, description) values (436, 'Aveeno Active Naturals Skin Relief Moisturizing', 'Durable non-stick frying pan for easy cooking and cleaning.');
insert into Equipment_Type (type_id, type_name, description) values (437, 'Antacid', 'Juicy and tender boneless chicken breasts.');
insert into Equipment_Type (type_id, type_name, description) values (438, 'Apanol', 'Crunchy granola clusters, perfect for snacking or topping yogurt.');
insert into Equipment_Type (type_id, type_name, description) values (439, 'Theophylline', 'Safety collar with flashing lights for pets during night walks.');
insert into Equipment_Type (type_id, type_name, description) values (440, 'Warfarin Sodium', 'Freshly roasted coffee beans with rich flavor.');
insert into Equipment_Type (type_id, type_name, description) values (441, 'Clear Eyes Complete 7 Sympton Relief', 'Grow herbs indoors with this easy-to-use hydroponic garden system.');
insert into Equipment_Type (type_id, type_name, description) values (442, 'ZOLPIDEM TARTRATE', 'Natural air purifiers to absorb odors and moisture.');
insert into Equipment_Type (type_id, type_name, description) values (443, 'CLARINS Extra-Comfort Broad Spectrum SPF 15 Sunscreen Tint 114', 'Warm oatmeal flavored with apple and cinnamon.');
insert into Equipment_Type (type_id, type_name, description) values (444, 'Natural Sunscreen Tan', 'Sweet and gooey cinnamon rolls, ready to bake.');
insert into Equipment_Type (type_id, type_name, description) values (445, '3 CONCEPT EYES SLIM FIT PACT NATURAL IVORY', 'Wireless microphone for singing and performances.');
insert into Equipment_Type (type_id, type_name, description) values (446, 'Lortab', 'Compact coffee grinder for fresh ground coffee beans.');
insert into Equipment_Type (type_id, type_name, description) values (447, 'Didanosine', 'Rechargeable electric wine opener for effortless uncorking.');
insert into Equipment_Type (type_id, type_name, description) values (448, 'SHISEIDO SHEER MATIFYING COMPACT (REFILL)', 'Nutty and chewy black rice, high in antioxidants.');
insert into Equipment_Type (type_id, type_name, description) values (449, 'Phenylephrine Hydrochloride', 'Durable skipping rope with adjustable length for workouts.');
insert into Equipment_Type (type_id, type_name, description) values (450, 'Anti-Aging Foundation SPF 15 Shade 800', 'Sweetened powder for refreshing lemonade.');
insert into Equipment_Type (type_id, type_name, description) values (451, 'Torsemide', 'Durable gardening gloves with reinforced fingertips.');
insert into Equipment_Type (type_id, type_name, description) values (452, 'Sleep Aid', 'Chewy granola bars made with honey and almonds.');
insert into Equipment_Type (type_id, type_name, description) values (453, 'Lemon', 'Floral and refreshing herbal tea, great hot or iced.');
insert into Equipment_Type (type_id, type_name, description) values (454, 'Desipramine Hydrochloride', 'Eco-friendly meal prep containers for healthy eating.');
insert into Equipment_Type (type_id, type_name, description) values (455, 'DEMEROL', 'Tool for measuring perfect pasta portions every time.');
insert into Equipment_Type (type_id, type_name, description) values (456, 'LBEL HYDRATESS', 'Creamy yogurt made with coconut and cashews, dairy-free.');
insert into Equipment_Type (type_id, type_name, description) values (457, 'BLACK HEAD REMOVER', 'Fluffy rice cooked with coconut milk for a tropical twist.');
insert into Equipment_Type (type_id, type_name, description) values (458, 'KIDS FIRST AID', 'A ready-to-eat soup with coconut milk, spices, and vegetables.');
insert into Equipment_Type (type_id, type_name, description) values (459, 'Comfort Pac with Naproxen', 'Marinated chicken grilled with lemon and herbs.');
insert into Equipment_Type (type_id, type_name, description) values (460, 'cold and cough daytime', 'Notepad made from recycled paper for sustainable note-taking.');
insert into Equipment_Type (type_id, type_name, description) values (461, 'Anastrozole', 'Wi-Fi enabled plug for controlling devices from your smartphone.');
insert into Equipment_Type (type_id, type_name, description) values (462, 'Zolpidem Tartrate', 'Portable folding table for outdoor events.');
insert into Equipment_Type (type_id, type_name, description) values (463, 'Zicam', 'Spicy and tangy chili sauce for adding heat to any dish.');
insert into Equipment_Type (type_id, type_name, description) values (464, 'Hydrocortisone', 'Soft and chewy bar packed with protein and cinnamon flavors.');
insert into Equipment_Type (type_id, type_name, description) values (465, 'LBEL HYDRATESS', 'A hearty soup made with organic lentils and vegetables.');
insert into Equipment_Type (type_id, type_name, description) values (466, 'YesTo Pomegranate Lip Butter with SPF 15', 'Quick meal kit with pasta and fresh vegetables.');
insert into Equipment_Type (type_id, type_name, description) values (467, 'Oxymorphone Hydrochloride', 'Frozen shrimp seasoned with chili and lime, perfect for quick dinners.');
insert into Equipment_Type (type_id, type_name, description) values (468, 'Bacteriostatic Water', 'A mix of strawberries, blueberries, and raspberries.');
insert into Equipment_Type (type_id, type_name, description) values (469, 'Elta Tar', 'Crispy mini pretzels, a great snack any time of day.');
insert into Equipment_Type (type_id, type_name, description) values (470, 'Good Sense Tussin CF', 'Set of decorative pillow covers to enhance your home decor.');
insert into Equipment_Type (type_id, type_name, description) values (471, 'Bupropion Hydrochloride', 'Set of decorative pillow covers to enhance your home decor.');
insert into Equipment_Type (type_id, type_name, description) values (472, 'Pain Relief Rub', 'Stay dry with these stylish waterproof rain boots.');
insert into Equipment_Type (type_id, type_name, description) values (473, 'Hydrocodone Bitartrate and Acetaminophen', 'Tofu stir-fried with fresh vegetables in teriyaki sauce.');
insert into Equipment_Type (type_id, type_name, description) values (474, 'Gyne-Lotrimin 3', 'Hearty minestrone soup loaded with vegetables and pasta.');
insert into Equipment_Type (type_id, type_name, description) values (475, 'LEVOXYL', 'Airtight container to keep pet food fresh.');
insert into Equipment_Type (type_id, type_name, description) values (476, 'Octreotide', 'Creamy goat cheese infused with herbs and garlic, perfect for spreading on crackers.');
insert into Equipment_Type (type_id, type_name, description) values (477, 'CEFOTAXIME', 'Custom keychain with engraved text.');
insert into Equipment_Type (type_id, type_name, description) values (478, 'Cetirizine Hydrochloride', 'Sanitary holder that ensures your toothbrush stays clean.');
insert into Equipment_Type (type_id, type_name, description) values (479, 'NoHist DM', 'Comfortable and warm leggings perfect for colder weather.');
insert into Equipment_Type (type_id, type_name, description) values (480, 'smart sense feminine', 'Convenient and low-carb alternative to traditional rice.');
insert into Equipment_Type (type_id, type_name, description) values (481, 'Aurum Prunus', 'Brews coffee with a smooth flavor without bitterness.');
insert into Equipment_Type (type_id, type_name, description) values (482, 'Lortab', 'Crunchy granola with maple flavor and almond pieces for breakfast.');
insert into Equipment_Type (type_id, type_name, description) values (483, 'Betamethasone Dipropionate', 'Effective laundry detergent for a deep clean.');
insert into Equipment_Type (type_id, type_name, description) values (484, 'Antiseptic', 'Organizational cubes for easy packing and travel.');
insert into Equipment_Type (type_id, type_name, description) values (485, 'HELMINTHOSPORIUM SOLANI', 'Tender ribs smothered in a honey barbecue sauce.');
insert into Equipment_Type (type_id, type_name, description) values (486, 'Glyburide', 'Protects surfaces while baking or cooking with hot items.');
insert into Equipment_Type (type_id, type_name, description) values (487, 'Stay Well', 'Low-carb pizza crust made from almond flour, gluten-free.');
insert into Equipment_Type (type_id, type_name, description) values (488, 'Simvastatin', 'All-in-one mix for easy homemade cheeseburgers, just add ground beef.');
insert into Equipment_Type (type_id, type_name, description) values (489, 'Colocynthis Kit Refill', 'Durable tablet designed for kids with parental controls.');
insert into Equipment_Type (type_id, type_name, description) values (490, 'Metoprolol Tartrate', 'Flexible LED lights for creative home lighting designs.');
insert into Equipment_Type (type_id, type_name, description) values (491, 'CV-Tone', 'Bright and fragrant cilantro, great for garnishes.');
insert into Equipment_Type (type_id, type_name, description) values (492, 'STUDIO FIX FLUID SPF 15 BROAD SPECTRUM', 'Set of two yoga blocks for increased stability and support.');
insert into Equipment_Type (type_id, type_name, description) values (493, 'LBEL EFFET PARFAIT Spots Reducing Effect Foundation SPF 18 - CLAIRE 4', 'Portable and lightweight umbrella for protection from rain.');
insert into Equipment_Type (type_id, type_name, description) values (494, 'IMITREX', 'A healthy vegan cheese alternative packed with nutrients and flavor.');
insert into Equipment_Type (type_id, type_name, description) values (495, 'Mesna', 'Chewy bars made with peanut butter and chocolate chips.');
insert into Equipment_Type (type_id, type_name, description) values (496, 'Pleo San Brucel', 'Compact fire pit for campfires and gatherings.');
insert into Equipment_Type (type_id, type_name, description) values (497, 'SUTENT', 'Quick oatmeal packets infused with apple and cinnamon, perfect for breakfast.');
insert into Equipment_Type (type_id, type_name, description) values (498, 'CRESTOR', 'Healthy energy bites made with oats and natural sweeteners.');
insert into Equipment_Type (type_id, type_name, description) values (499, 'R2 Skin Protectant', 'Delicious clusters of peanuts and chocolate for a sweet treat.');
insert into Equipment_Type (type_id, type_name, description) values (500, 'Theophylline Extended Release', 'Nutritious and quick-cooking red lentils.');
