insert into Mission (mission_id, mission_name, mission_date, location) values (1, 'Hydrocodone Bitartrate and Ibuprofen', '11/13/2024', '7267 Calypso Pass');
insert into Mission (mission_id, mission_name, mission_date, location) values (2, 'PCXX ONE MINTE GEL MOCHA CAPPUCCINO', '2/24/2025', '5898 Barby Drive');
insert into Mission (mission_id, mission_name, mission_date, location) values (3, 'EPOGEN', '5/24/2024', '3428 Oak Way');
insert into Mission (mission_id, mission_name, mission_date, location) values (4, 'Promethazine Hydrochloride', '8/3/2024', '5 Stone Corner Junction');
insert into Mission (mission_id, mission_name, mission_date, location) values (5, 'Acyclovir', '1/3/2025', '26 Hauk Road');
insert into Mission (mission_id, mission_name, mission_date, location) values (6, 'Neurontin', '2/26/2025', '7 Morningstar Park');
insert into Mission (mission_id, mission_name, mission_date, location) values (7, 'Levothyroxine Sodium', '4/22/2024', '5 Dapin Court');
insert into Mission (mission_id, mission_name, mission_date, location) values (8, 'Se-Care Chewable', '3/12/2025', '0064 Orin Center');
insert into Mission (mission_id, mission_name, mission_date, location) values (9, 'SIMPEX Bisacodyl laxative', '9/12/2024', '354 Northport Street');
insert into Mission (mission_id, mission_name, mission_date, location) values (10, 'Vecuronium Bromide', '3/22/2025', '9516 Barnett Circle');
insert into Mission (mission_id, mission_name, mission_date, location) values (11, 'Byetta', '5/30/2024', '5 Novick Park');
insert into Mission (mission_id, mission_name, mission_date, location) values (12, 'Dexmethylphenidate Hydrochloride', '10/20/2024', '7 Spohn Place');
insert into Mission (mission_id, mission_name, mission_date, location) values (13, 'SHISEIDO RADIANT LIFTING FOUNDATION', '8/29/2024', '55335 Center Junction');
insert into Mission (mission_id, mission_name, mission_date, location) values (14, 'TELMISARTAN', '11/28/2024', '3883 Forest Run Hill');
insert into Mission (mission_id, mission_name, mission_date, location) values (15, 'Doxycycline Hyclate', '6/18/2024', '38 Golf Road');
insert into Mission (mission_id, mission_name, mission_date, location) values (16, 'Methotrexate', '9/17/2024', '08087 Kropf Court');
insert into Mission (mission_id, mission_name, mission_date, location) values (17, 'Silver Sulfadiazine', '11/13/2024', '089 Chive Road');
insert into Mission (mission_id, mission_name, mission_date, location) values (18, 'Careone Acid Reducer', '8/13/2024', '06 Havey Terrace');
insert into Mission (mission_id, mission_name, mission_date, location) values (19, 'TC EnrichedFoam', '1/20/2025', '5 Butterfield Crossing');
insert into Mission (mission_id, mission_name, mission_date, location) values (20, 'Natural Fluoride Fresh Mint', '1/8/2025', '7 Farmco Place');
insert into Mission (mission_id, mission_name, mission_date, location) values (21, 'Ondansetron', '10/25/2024', '91497 Luster Crossing');
insert into Mission (mission_id, mission_name, mission_date, location) values (22, 'Head and Shoulders', '9/17/2024', '1298 Marquette Center');
insert into Mission (mission_id, mission_name, mission_date, location) values (23, 'ARSENICUM ALBUM', '11/15/2024', '56 Tennessee Pass');
insert into Mission (mission_id, mission_name, mission_date, location) values (24, 'CitraNatal Harmony', '8/29/2024', '93335 Pleasure Terrace');
insert into Mission (mission_id, mission_name, mission_date, location) values (25, 'Carvedilol', '1/24/2025', '72786 Knutson Alley');
insert into Mission (mission_id, mission_name, mission_date, location) values (26, 'Lithium', '12/11/2024', '2650 Clove Trail');
insert into Mission (mission_id, mission_name, mission_date, location) values (27, 'Amoxicillin', '5/25/2024', '6 Pond Crossing');
insert into Mission (mission_id, mission_name, mission_date, location) values (28, 'Babyganics', '8/2/2024', '8716 Killdeer Park');
insert into Mission (mission_id, mission_name, mission_date, location) values (29, 'Walgreens SUNSCREEN Sport', '7/27/2024', '2666 Orin Avenue');
insert into Mission (mission_id, mission_name, mission_date, location) values (30, 'Diovan', '9/29/2024', '599 Mariners Cove Trail');
insert into Mission (mission_id, mission_name, mission_date, location) values (31, 'Verapamil Hydrochloride', '7/10/2024', '51 Glacier Hill Lane');
insert into Mission (mission_id, mission_name, mission_date, location) values (32, 'ZOVIRAX', '9/12/2024', '29110 Mendota Place');
insert into Mission (mission_id, mission_name, mission_date, location) values (33, 'THAM', '5/18/2024', '12183 Maple Wood Plaza');
insert into Mission (mission_id, mission_name, mission_date, location) values (34, 'Captopril', '8/1/2024', '766 Knutson Junction');
insert into Mission (mission_id, mission_name, mission_date, location) values (35, 'Levothyroxine Sodium', '6/17/2024', '458 Bobwhite Park');
insert into Mission (mission_id, mission_name, mission_date, location) values (36, 'LISINOPRIL AND HYDROCHLOROTHIAZIDE', '6/6/2024', '89 Shopko Pass');
insert into Mission (mission_id, mission_name, mission_date, location) values (37, 'Tretinoin', '5/26/2024', '30 Claremont Alley');
insert into Mission (mission_id, mission_name, mission_date, location) values (38, 'DARAPRIM', '8/23/2024', '192 Oakridge Place');
insert into Mission (mission_id, mission_name, mission_date, location) values (39, 'Comfort Pac with Meloxicam', '12/30/2024', '449 Dennis Center');
insert into Mission (mission_id, mission_name, mission_date, location) values (40, 'Cold-EEZE', '11/30/2024', '34 Maryland Road');
insert into Mission (mission_id, mission_name, mission_date, location) values (41, 'Oxycodone and Acetaminophen', '8/3/2024', '5990 Farwell Pass');
insert into Mission (mission_id, mission_name, mission_date, location) values (42, '7 Select Migraine Formula', '2/19/2025', '32 Prentice Park');
insert into Mission (mission_id, mission_name, mission_date, location) values (43, 'Paroxetine', '12/6/2024', '94 Donald Plaza');
insert into Mission (mission_id, mission_name, mission_date, location) values (44, 'Grippe HP', '10/8/2024', '0931 Memorial Place');
insert into Mission (mission_id, mission_name, mission_date, location) values (45, 'risperidone', '2/7/2025', '8984 Sunnyside Park');
insert into Mission (mission_id, mission_name, mission_date, location) values (46, 'Ibuprofen', '9/16/2024', '9239 Roxbury Alley');
insert into Mission (mission_id, mission_name, mission_date, location) values (47, 'BAC', '3/3/2025', '86427 Riverside Junction');
insert into Mission (mission_id, mission_name, mission_date, location) values (48, 'ZYPREXA', '6/1/2024', '39257 Sunbrook Trail');
insert into Mission (mission_id, mission_name, mission_date, location) values (49, 'LEADER ANTI ITCH MAXIMUM STRENGTH', '12/17/2024', '628 Blaine Hill');
insert into Mission (mission_id, mission_name, mission_date, location) values (50, 'Citalopram Hydrobromide', '10/30/2024', '967 Schmedeman Hill');
insert into Mission (mission_id, mission_name, mission_date, location) values (51, 'Levothyroxine sodium', '7/10/2024', '3561 Killdeer Crossing');
insert into Mission (mission_id, mission_name, mission_date, location) values (52, 'TC EnrichedFoam', '10/7/2024', '97 Canary Street');
insert into Mission (mission_id, mission_name, mission_date, location) values (53, 'ibuprofen', '4/27/2024', '4 Buell Lane');
insert into Mission (mission_id, mission_name, mission_date, location) values (54, 'Montelukast Sodium', '3/5/2025', '34023 Mifflin Avenue');
insert into Mission (mission_id, mission_name, mission_date, location) values (55, 'ULTRAM ER', '3/18/2025', '9250 Ryan Alley');
insert into Mission (mission_id, mission_name, mission_date, location) values (56, 'PROPECIA', '6/26/2024', '0 Hanson Circle');
insert into Mission (mission_id, mission_name, mission_date, location) values (57, 'Ampicillin and Sulbactam', '1/4/2025', '0073 Debs Place');
insert into Mission (mission_id, mission_name, mission_date, location) values (58, 'DIGOX', '9/11/2024', '943 Killdeer Lane');
insert into Mission (mission_id, mission_name, mission_date, location) values (59, 'Hydroxyzine', '5/1/2024', '05 Magdeline Park');
insert into Mission (mission_id, mission_name, mission_date, location) values (60, 'Bambusa Rhus', '10/8/2024', '2690 Alpine Court');
insert into Mission (mission_id, mission_name, mission_date, location) values (61, 'CAFFEINE CITRATE', '5/31/2024', '51 Nancy Circle');
insert into Mission (mission_id, mission_name, mission_date, location) values (62, 'Day Time Cold and Flu Relief', '1/28/2025', '5 Graceland Pass');
insert into Mission (mission_id, mission_name, mission_date, location) values (63, 'MARCS', '5/14/2024', '4356 Independence Crossing');
insert into Mission (mission_id, mission_name, mission_date, location) values (64, 'MENTAL ALERTNESS SUPPORT', '7/2/2024', '4 Schmedeman Point');
insert into Mission (mission_id, mission_name, mission_date, location) values (65, 'Andalou BB sheer tint with SPF-30', '4/16/2024', '84733 Oak Circle');
insert into Mission (mission_id, mission_name, mission_date, location) values (66, 'Neomycin and Polymyxin B Sulfates', '9/29/2024', '8 Lunder Court');
insert into Mission (mission_id, mission_name, mission_date, location) values (67, 'Natures Gate', '6/28/2024', '0113 Lindbergh Terrace');
insert into Mission (mission_id, mission_name, mission_date, location) values (68, 'Imipenem and Cilastatin', '6/25/2024', '141 American Ash Point');
insert into Mission (mission_id, mission_name, mission_date, location) values (69, 'EROS AQUA BASED', '10/10/2024', '25131 1st Drive');
insert into Mission (mission_id, mission_name, mission_date, location) values (70, 'Gris-PEG', '7/2/2024', '48600 Tennessee Court');
insert into Mission (mission_id, mission_name, mission_date, location) values (71, 'ADSOL Red Cell Preservation Solution System in Plastic Container (PL 146 Plastic)', '10/29/2024', '45611 Laurel Parkway');
insert into Mission (mission_id, mission_name, mission_date, location) values (72, 'Amoxicillin and Clavulanate Potassium', '11/18/2024', '99 Westend Terrace');
insert into Mission (mission_id, mission_name, mission_date, location) values (73, 'SLEEP AID', '5/22/2024', '2919 Namekagon Terrace');
insert into Mission (mission_id, mission_name, mission_date, location) values (74, 'Midazolam Hydrochloride', '9/15/2024', '43825 Roth Center');
insert into Mission (mission_id, mission_name, mission_date, location) values (75, 'Icewave', '6/1/2024', '38908 Crownhardt Crossing');
insert into Mission (mission_id, mission_name, mission_date, location) values (76, 'OXYGEN', '12/9/2024', '9 Haas Junction');
insert into Mission (mission_id, mission_name, mission_date, location) values (77, 'Oil-Free Foaming Acne Wash Facial Cleanser', '12/20/2024', '39 High Crossing Place');
insert into Mission (mission_id, mission_name, mission_date, location) values (78, 'Mosquito', '2/22/2025', '25 Maple Wood Road');
insert into Mission (mission_id, mission_name, mission_date, location) values (79, 'AZELEX', '8/11/2024', '262 Weeping Birch Plaza');
insert into Mission (mission_id, mission_name, mission_date, location) values (80, 'Albuterol Sulfate', '9/28/2024', '605 Mcguire Place');
insert into Mission (mission_id, mission_name, mission_date, location) values (81, 'Fentanyl', '6/11/2024', '118 Maryland Court');
insert into Mission (mission_id, mission_name, mission_date, location) values (82, 'RENEWAL', '3/5/2025', '6022 Nobel Crossing');
insert into Mission (mission_id, mission_name, mission_date, location) values (83, 'SBS 41 Medicated Cream', '6/3/2024', '967 Dawn Way');
insert into Mission (mission_id, mission_name, mission_date, location) values (84, 'Tasigna', '12/21/2024', '6884 Dixon Pass');
insert into Mission (mission_id, mission_name, mission_date, location) values (85, 'Food - Plant Source, Pecan Carya illinoensis', '12/19/2024', '488 Clemons Point');
insert into Mission (mission_id, mission_name, mission_date, location) values (86, 'Ketek', '8/17/2024', '7477 Bobwhite Point');
insert into Mission (mission_id, mission_name, mission_date, location) values (87, 'Baclofen', '10/13/2024', '1632 Banding Park');
insert into Mission (mission_id, mission_name, mission_date, location) values (88, 'HAND AND NATURE SANITIZER', '7/13/2024', '282 Brickson Park Hill');
insert into Mission (mission_id, mission_name, mission_date, location) values (89, 'Ampicillin and Sulbactam', '8/28/2024', '2975 Granby Point');
insert into Mission (mission_id, mission_name, mission_date, location) values (90, 'Earache', '2/6/2025', '97 Mandrake Circle');
insert into Mission (mission_id, mission_name, mission_date, location) values (91, 'Lisinopril', '4/25/2024', '292 Declaration Road');
insert into Mission (mission_id, mission_name, mission_date, location) values (92, 'EuCutaSol', '10/31/2024', '041 Jana Drive');
insert into Mission (mission_id, mission_name, mission_date, location) values (93, 'Lisinopril and Hydrochlorothiazide', '10/14/2024', '3560 Homewood Parkway');
insert into Mission (mission_id, mission_name, mission_date, location) values (94, 'MedPride', '2/7/2025', '2746 Morning Way');
insert into Mission (mission_id, mission_name, mission_date, location) values (95, 'Hourglass Illusion Tinted Moisturizer Sand', '2/25/2025', '16378 Burrows Street');
insert into Mission (mission_id, mission_name, mission_date, location) values (96, 'Metoclopramide', '9/28/2024', '2992 Gateway Terrace');
insert into Mission (mission_id, mission_name, mission_date, location) values (97, 'Nephrocaps-QT', '3/30/2025', '2 Maple Trail');
insert into Mission (mission_id, mission_name, mission_date, location) values (98, 'Guanfacine', '9/28/2024', '673 Ruskin Trail');
insert into Mission (mission_id, mission_name, mission_date, location) values (99, 'VERATRUM ALBUM', '6/21/2024', '5 Atwood Point');
insert into Mission (mission_id, mission_name, mission_date, location) values (100, 'Diovan', '9/8/2024', '51232 Lerdahl Hill');
insert into Mission (mission_id, mission_name, mission_date, location) values (101, 'Ventavis', '7/25/2024', '89111 Lakewood Gardens Circle');
insert into Mission (mission_id, mission_name, mission_date, location) values (102, 'Imipramine Hydrochloride', '8/19/2024', '975 Granby Park');
insert into Mission (mission_id, mission_name, mission_date, location) values (103, 'Instant Hand Sanitizer', '7/13/2024', '855 Judy Parkway');
insert into Mission (mission_id, mission_name, mission_date, location) values (104, 'Gold Antibacterial Hand Soap with Moisturizer', '2/19/2025', '9322 Schiller Crossing');
insert into Mission (mission_id, mission_name, mission_date, location) values (105, 'ROPINIROLE HYDROCHLORIDE', '1/29/2025', '517 Service Crossing');
insert into Mission (mission_id, mission_name, mission_date, location) values (106, 'Berkley and Jensen Acid Controller', '3/12/2025', '6496 Monterey Junction');
insert into Mission (mission_id, mission_name, mission_date, location) values (107, 'Amlodipine Besylate', '5/2/2024', '4 Melrose Drive');
insert into Mission (mission_id, mission_name, mission_date, location) values (108, 'Morning Sickness Relief', '7/2/2024', '7 Hanson Road');
insert into Mission (mission_id, mission_name, mission_date, location) values (109, 'Hand Wash Nettoyant Pour Les Mains Citrus Cilantro', '7/8/2024', '18686 Oak Drive');
insert into Mission (mission_id, mission_name, mission_date, location) values (110, 'Ailanthus', '10/14/2024', '39048 Alpine Street');
insert into Mission (mission_id, mission_name, mission_date, location) values (111, 'Syncol', '2/22/2025', '6282 Blaine Park');
insert into Mission (mission_id, mission_name, mission_date, location) values (112, 'Pediaderm HC', '12/20/2024', '5 Messerschmidt Trail');
insert into Mission (mission_id, mission_name, mission_date, location) values (113, 'No Foundation Foundation Fair', '7/7/2024', '0993 Mallory Road');
insert into Mission (mission_id, mission_name, mission_date, location) values (114, 'Glucotrol XL', '5/7/2024', '04425 Florence Lane');
insert into Mission (mission_id, mission_name, mission_date, location) values (115, 'Theophylline', '7/4/2024', '956 Mallory Plaza');
insert into Mission (mission_id, mission_name, mission_date, location) values (116, 'Alprazolam', '7/22/2024', '1288 Sachs Alley');
insert into Mission (mission_id, mission_name, mission_date, location) values (117, 'Vyvanse', '1/18/2025', '55 Elmside Place');
insert into Mission (mission_id, mission_name, mission_date, location) values (118, 'BABOR Cleansing Mild Peeling', '7/13/2024', '3 Nelson Circle');
insert into Mission (mission_id, mission_name, mission_date, location) values (119, 'Pentoxifylline', '10/8/2024', '6401 Mendota Alley');
insert into Mission (mission_id, mission_name, mission_date, location) values (120, 'Floxuridine', '2/28/2025', '55 Chinook Street');
insert into Mission (mission_id, mission_name, mission_date, location) values (121, 'Enalapril Maleate', '12/13/2024', '9708 Amoth Circle');
insert into Mission (mission_id, mission_name, mission_date, location) values (122, 'Lansoprazole', '7/15/2024', '997 Killdeer Junction');
insert into Mission (mission_id, mission_name, mission_date, location) values (123, 'Instant Hand Sanitizer', '5/24/2024', '0452 Corry Alley');
insert into Mission (mission_id, mission_name, mission_date, location) values (124, 'Valacyclovir', '7/14/2024', '29220 Rockefeller Crossing');
insert into Mission (mission_id, mission_name, mission_date, location) values (125, 'Benzoin Compound Tincture Professional Pack', '4/26/2024', '1007 Jenifer Drive');
insert into Mission (mission_id, mission_name, mission_date, location) values (126, 'Neutrogena Beach Defense Water Plus Sun Barrier', '3/22/2025', '89 Dawn Road');
insert into Mission (mission_id, mission_name, mission_date, location) values (127, 'Doxycycline Hyclate', '5/3/2024', '14 4th Center');
insert into Mission (mission_id, mission_name, mission_date, location) values (128, 'CAPTOPRIL', '5/7/2024', '139 Autumn Leaf Lane');
insert into Mission (mission_id, mission_name, mission_date, location) values (129, 'Coreg', '12/26/2024', '070 Kensington Park');
insert into Mission (mission_id, mission_name, mission_date, location) values (130, 'Stay Alert Aid', '7/7/2024', '41799 Kropf Lane');
insert into Mission (mission_id, mission_name, mission_date, location) values (131, 'Desloratadine', '4/16/2024', '00 Sachtjen Court');
insert into Mission (mission_id, mission_name, mission_date, location) values (132, 'Covergirl Queen Collection All Day Flawless 3in1 Foundation', '2/10/2025', '1 Rusk Way');
insert into Mission (mission_id, mission_name, mission_date, location) values (133, 'Anti-Perspirant Deodorant', '11/22/2024', '00 Kingsford Plaza');
insert into Mission (mission_id, mission_name, mission_date, location) values (134, 'SuperPlus Beblesh Balm Triple Functions SPF25 PA 2Plus', '10/2/2024', '98042 Summit Drive');
insert into Mission (mission_id, mission_name, mission_date, location) values (135, 'Ibuprofen', '7/18/2024', '26 Clyde Gallagher Pass');
insert into Mission (mission_id, mission_name, mission_date, location) values (136, 'Complete Lice Treatment', '10/30/2024', '615 South Trail');
insert into Mission (mission_id, mission_name, mission_date, location) values (137, 'Rubus', '4/20/2024', '80080 East Court');
insert into Mission (mission_id, mission_name, mission_date, location) values (138, 'Anti-Bac Concentrate', '9/23/2024', '9 Mifflin Road');
insert into Mission (mission_id, mission_name, mission_date, location) values (139, 'Nimodipine', '10/7/2024', '284 Ridgeway Hill');
insert into Mission (mission_id, mission_name, mission_date, location) values (140, 'Verapamil Hydrochloride', '3/3/2025', '16055 Grasskamp Pass');
insert into Mission (mission_id, mission_name, mission_date, location) values (141, 'Levofloxacin', '7/27/2024', '68 Birchwood Street');
insert into Mission (mission_id, mission_name, mission_date, location) values (142, 'QUERCUS ALBA POLLEN', '9/6/2024', '29 Monterey Hill');
insert into Mission (mission_id, mission_name, mission_date, location) values (143, 'Spatheraphy', '10/24/2024', '3010 Hoard Trail');
insert into Mission (mission_id, mission_name, mission_date, location) values (144, 'Leader Ibuprofen', '11/19/2024', '1582 Mandrake Park');
insert into Mission (mission_id, mission_name, mission_date, location) values (145, 'Eggplant', '3/11/2025', '6514 Katie Street');
insert into Mission (mission_id, mission_name, mission_date, location) values (146, 'MK Alcohol Prep Pads Medium', '11/28/2024', '604 Fuller Alley');
insert into Mission (mission_id, mission_name, mission_date, location) values (147, 'Candida albicans', '11/8/2024', '38478 Crowley Way');
insert into Mission (mission_id, mission_name, mission_date, location) values (148, 'Clorazepate Dipotassium', '4/10/2024', '646 Tomscot Pass');
insert into Mission (mission_id, mission_name, mission_date, location) values (149, 'TRAMADOL HYDROCHLORIDE', '5/7/2024', '830 Sheridan Terrace');
insert into Mission (mission_id, mission_name, mission_date, location) values (150, 'Lyrica', '2/20/2025', '78564 Crownhardt Plaza');
insert into Mission (mission_id, mission_name, mission_date, location) values (151, 'Terrasil Rapid-Relief Vaginal', '4/27/2024', '24 Del Sol Circle');
insert into Mission (mission_id, mission_name, mission_date, location) values (152, 'Nitro-Time', '4/22/2024', '88 Holy Cross Alley');
insert into Mission (mission_id, mission_name, mission_date, location) values (153, 'Levetiracetam', '4/28/2024', '87090 Green Place');
insert into Mission (mission_id, mission_name, mission_date, location) values (154, 'Mineral Oil', '4/4/2025', '85 Menomonie Lane');
insert into Mission (mission_id, mission_name, mission_date, location) values (155, 'BOTANICAL FRESH BB SET', '7/18/2024', '142 Nancy Parkway');
insert into Mission (mission_id, mission_name, mission_date, location) values (156, 'Treatment Set TS335683', '11/17/2024', '9 Sullivan Pass');
insert into Mission (mission_id, mission_name, mission_date, location) values (157, 'Isosorbide Dinitrate', '5/1/2024', '288 Atwood Terrace');
insert into Mission (mission_id, mission_name, mission_date, location) values (158, 'Triamterene and Hydrochlorothiazide', '12/12/2024', '4019 Cascade Junction');
insert into Mission (mission_id, mission_name, mission_date, location) values (159, 'harmon face values omeprazole', '11/3/2024', '33332 Badeau Circle');
insert into Mission (mission_id, mission_name, mission_date, location) values (160, 'Air', '3/28/2025', '757 Becker Junction');
insert into Mission (mission_id, mission_name, mission_date, location) values (161, 'Topicort', '10/4/2024', '86 Nevada Lane');
insert into Mission (mission_id, mission_name, mission_date, location) values (162, 'Ranitidine Hydrochloride', '7/31/2024', '8 Eliot Terrace');
insert into Mission (mission_id, mission_name, mission_date, location) values (163, 'Ipratropium Bromide and Albuterol Sulfate', '1/15/2025', '5 Corben Terrace');
insert into Mission (mission_id, mission_name, mission_date, location) values (164, 'BIOSOLIS Sun Milk UVA Sunscreen Face and Body Broad Spectrum SPF15', '10/28/2024', '81 Eagle Crest Junction');
insert into Mission (mission_id, mission_name, mission_date, location) values (165, 'Oxymetazoline Hydrochloride', '5/24/2024', '89958 Independence Way');
insert into Mission (mission_id, mission_name, mission_date, location) values (166, 'Ondansetron', '3/19/2025', '3693 Caliangt Point');
insert into Mission (mission_id, mission_name, mission_date, location) values (167, 'Dantrolene Sodium', '2/7/2025', '86 Browning Way');
insert into Mission (mission_id, mission_name, mission_date, location) values (168, 'Azolen', '7/16/2024', '0761 Tennessee Lane');
insert into Mission (mission_id, mission_name, mission_date, location) values (169, 'Quinapril', '3/9/2025', '0 Weeping Birch Circle');
insert into Mission (mission_id, mission_name, mission_date, location) values (170, 'Vivactil', '5/27/2024', '8502 Bayside Hill');
insert into Mission (mission_id, mission_name, mission_date, location) values (171, 'Finasteride', '3/6/2025', '3757 Meadow Vale Lane');
insert into Mission (mission_id, mission_name, mission_date, location) values (172, 'Mucinex Fast-Max', '4/15/2024', '4 Pawling Pass');
insert into Mission (mission_id, mission_name, mission_date, location) values (173, 'METOPROLOL SUCCINATE', '7/31/2024', '9472 Graceland Court');
insert into Mission (mission_id, mission_name, mission_date, location) values (174, 'Gabapentin', '5/2/2024', '27 Schmedeman Hill');
insert into Mission (mission_id, mission_name, mission_date, location) values (175, 'Bio Sweet Chestnut', '7/31/2024', '5986 Cardinal Crossing');
insert into Mission (mission_id, mission_name, mission_date, location) values (176, 'Ciclopirox', '1/15/2025', '54 Basil Point');
insert into Mission (mission_id, mission_name, mission_date, location) values (177, 'Hemoforce', '4/26/2024', '21920 Burrows Place');
insert into Mission (mission_id, mission_name, mission_date, location) values (178, 'Irbesartan', '4/13/2024', '243 Lien Way');
insert into Mission (mission_id, mission_name, mission_date, location) values (179, 'Up and Up Acid Reducer', '3/15/2025', '8067 Barby Road');
insert into Mission (mission_id, mission_name, mission_date, location) values (180, 'Enoxaparin Sodium', '8/12/2024', '87044 Kropf Crossing');
insert into Mission (mission_id, mission_name, mission_date, location) values (181, 'fiteBac SkinCare', '10/8/2024', '23342 Stuart Street');
insert into Mission (mission_id, mission_name, mission_date, location) values (182, 'Up and Up Ibuprofen', '10/15/2024', '05029 Fairview Alley');
insert into Mission (mission_id, mission_name, mission_date, location) values (183, 'LEVOBUNOLOL HYDROCHLORIDE', '9/12/2024', '28 Waubesa Place');
insert into Mission (mission_id, mission_name, mission_date, location) values (184, 'White Fish', '1/30/2025', '14957 Clyde Gallagher Circle');
insert into Mission (mission_id, mission_name, mission_date, location) values (185, 'womens laxative', '7/7/2024', '02 Sugar Court');
insert into Mission (mission_id, mission_name, mission_date, location) values (186, 'Amidate', '1/13/2025', '8614 Mayfield Circle');
insert into Mission (mission_id, mission_name, mission_date, location) values (187, 'Mulling Spices Antibacterial Foaming Hand Wash', '12/10/2024', '32 Vernon Point');
insert into Mission (mission_id, mission_name, mission_date, location) values (188, 'EPIVIR', '5/20/2024', '2 David Street');
insert into Mission (mission_id, mission_name, mission_date, location) values (189, 'Losartan Potassium and Hydrochlorothiazide', '9/21/2024', '59226 Graedel Road');
insert into Mission (mission_id, mission_name, mission_date, location) values (190, 'Childrens Nortemp', '5/28/2024', '4458 Lien Lane');
insert into Mission (mission_id, mission_name, mission_date, location) values (191, 'Glyburide-Metformin Hydrochloride', '5/3/2024', '1194 Manufacturers Court');
insert into Mission (mission_id, mission_name, mission_date, location) values (192, 'Red Alder', '5/9/2024', '77 Fair Oaks Road');
insert into Mission (mission_id, mission_name, mission_date, location) values (193, 'MEDI-FIRST Aspirin', '4/9/2024', '5 Harbort Point');
insert into Mission (mission_id, mission_name, mission_date, location) values (194, 'Mango Blossom', '6/29/2024', '017 Eliot Way');
insert into Mission (mission_id, mission_name, mission_date, location) values (195, 'Diphenhydramine Hydrochloride', '2/15/2025', '2 Anzinger Point');
insert into Mission (mission_id, mission_name, mission_date, location) values (196, 'topcare childrens mucus relief multi symptom cold', '8/31/2024', '13771 Fisk Plaza');
insert into Mission (mission_id, mission_name, mission_date, location) values (197, 'Anti-Bacterial Hand', '9/1/2024', '5588 Haas Street');
insert into Mission (mission_id, mission_name, mission_date, location) values (198, 'Thyrotox', '2/15/2025', '7 Farmco Terrace');
insert into Mission (mission_id, mission_name, mission_date, location) values (199, 'Doxercalciferol', '8/14/2024', '3216 Ridge Oak Parkway');
insert into Mission (mission_id, mission_name, mission_date, location) values (200, 'TENUE DE PERFECTION TIMEPROOF FOUNDATION WITH SUNSCREEN ULTIMATE LASTING PERFECTION BROAD SPECTRUM SPF 20 13 ROSE NATUREL', '5/8/2024', '3536 Jenifer Point');
insert into Mission (mission_id, mission_name, mission_date, location) values (201, 'Chinese Elm', '11/26/2024', '7 Reinke Junction');
insert into Mission (mission_id, mission_name, mission_date, location) values (202, 'Vichy Normaderm', '12/15/2024', '24987 Becker Junction');
insert into Mission (mission_id, mission_name, mission_date, location) values (203, 'Treatment Set TS333312', '11/23/2024', '999 Nova Trail');
insert into Mission (mission_id, mission_name, mission_date, location) values (204, 'Propranolol Hydrochloride', '9/2/2024', '713 Anhalt Terrace');
insert into Mission (mission_id, mission_name, mission_date, location) values (205, 'Glimepiride', '10/30/2024', '79129 Corben Trail');
insert into Mission (mission_id, mission_name, mission_date, location) values (206, 'Hydrocortisone', '6/15/2024', '27 Westend Court');
insert into Mission (mission_id, mission_name, mission_date, location) values (207, 'Romazicon', '6/2/2024', '2 Kensington Plaza');
insert into Mission (mission_id, mission_name, mission_date, location) values (208, 'Acid Reducer', '6/13/2024', '33 Green Ridge Court');
insert into Mission (mission_id, mission_name, mission_date, location) values (209, 'Neutrogena Blackhead Eliminating Daily Scrub', '5/1/2024', '90126 Paget Terrace');
insert into Mission (mission_id, mission_name, mission_date, location) values (210, 'ShopRite Ni Calm', '4/28/2024', '45 Clove Alley');
insert into Mission (mission_id, mission_name, mission_date, location) values (211, 'Mary Kay Tinted Lip Balm Sunscreen SPF 15 Berry', '5/17/2024', '189 Northridge Street');
insert into Mission (mission_id, mission_name, mission_date, location) values (212, 'Tizanidine', '10/20/2024', '3117 Shoshone Trail');
insert into Mission (mission_id, mission_name, mission_date, location) values (213, 'MIDODRINE HYDROCHLORIDE', '1/27/2025', '515 Main Junction');
insert into Mission (mission_id, mission_name, mission_date, location) values (214, 'Technetium Tc99m Generator', '9/13/2024', '09074 Stoughton Plaza');
insert into Mission (mission_id, mission_name, mission_date, location) values (215, 'Renew Dimethicone Skin Protectant', '5/22/2024', '27 Duke Parkway');
insert into Mission (mission_id, mission_name, mission_date, location) values (216, 'APINOPHEN', '12/1/2024', '37553 Packers Plaza');
insert into Mission (mission_id, mission_name, mission_date, location) values (217, 'Food - Plant Source, Strawberry Fragaria chiloensis', '9/9/2024', '385 Golf Course Circle');
insert into Mission (mission_id, mission_name, mission_date, location) values (218, 'Triamcinolone Acetonide', '3/19/2025', '4 Harper Circle');
insert into Mission (mission_id, mission_name, mission_date, location) values (219, 'Photocil', '11/20/2024', '4241 Londonderry Pass');
insert into Mission (mission_id, mission_name, mission_date, location) values (220, 'SUSTIVA', '11/15/2024', '447 Havey Trail');
insert into Mission (mission_id, mission_name, mission_date, location) values (221, 'Scilla Crataegus', '5/25/2024', '87 Mockingbird Parkway');
insert into Mission (mission_id, mission_name, mission_date, location) values (222, 'ABILIFY', '3/10/2025', '067 Walton Hill');
insert into Mission (mission_id, mission_name, mission_date, location) values (223, 'Eve Lom Radiance Lift Foundation SPF 15', '11/9/2024', '40 Drewry Point');
insert into Mission (mission_id, mission_name, mission_date, location) values (224, 'Mucus Relief Cold, Flu and Sore Throat', '12/23/2024', '0567 Kedzie Crossing');
insert into Mission (mission_id, mission_name, mission_date, location) values (225, 'Cefaclor', '2/1/2025', '3219 Armistice Alley');
insert into Mission (mission_id, mission_name, mission_date, location) values (226, 'Propranolol Hydrochloride', '10/11/2024', '0907 Mcbride Parkway');
insert into Mission (mission_id, mission_name, mission_date, location) values (227, 'rocuronium bromide', '7/20/2024', '35185 Vahlen Center');
insert into Mission (mission_id, mission_name, mission_date, location) values (228, 'Equate Hemorrhoidal Medicated Wipes', '10/28/2024', '7248 Sage Drive');
insert into Mission (mission_id, mission_name, mission_date, location) values (229, 'Quetiapine Fumarate', '7/1/2024', '9 Artisan Pass');
insert into Mission (mission_id, mission_name, mission_date, location) values (230, 'leader nose', '5/12/2024', '81 Gina Point');
insert into Mission (mission_id, mission_name, mission_date, location) values (231, 'SHISEIDO WHITE LUCENT BRIGHTENING SPOT-CONTROL FOUNDATION (REFILL)', '4/19/2024', '436 New Castle Point');
insert into Mission (mission_id, mission_name, mission_date, location) values (232, 'Diltiazem Hydrochloride', '4/3/2025', '20 Karstens Drive');
insert into Mission (mission_id, mission_name, mission_date, location) values (233, 'nifedipine', '5/12/2024', '1 Nova Terrace');
insert into Mission (mission_id, mission_name, mission_date, location) values (234, 'Salsalate', '11/30/2024', '58 La Follette Center');
insert into Mission (mission_id, mission_name, mission_date, location) values (235, 'Noxzema', '1/19/2025', '1779 Delaware Terrace');
insert into Mission (mission_id, mission_name, mission_date, location) values (236, 'Skyline Antibacterial Hand Cleanser', '5/21/2024', '572 Fair Oaks Parkway');
insert into Mission (mission_id, mission_name, mission_date, location) values (237, 'Staples Instant Hand Sanitizer', '3/29/2025', '66 Becker Crossing');
insert into Mission (mission_id, mission_name, mission_date, location) values (238, 'Peptic Relief', '3/24/2025', '55172 Dapin Alley');
insert into Mission (mission_id, mission_name, mission_date, location) values (239, 'LBEL COULEUR LUXE AMPLIFIER XP', '11/2/2024', '26 South Parkway');
insert into Mission (mission_id, mission_name, mission_date, location) values (240, 'KALI PHOSPHORICUM', '12/10/2024', '57 Tomscot Drive');
insert into Mission (mission_id, mission_name, mission_date, location) values (241, 'TOPIRAMATE', '9/20/2024', '929 Canary Junction');
insert into Mission (mission_id, mission_name, mission_date, location) values (242, 'Metoprolol Tartrate', '7/22/2024', '43885 6th Parkway');
insert into Mission (mission_id, mission_name, mission_date, location) values (243, 'Zatean-CH', '10/4/2024', '8363 Vidon Junction');
insert into Mission (mission_id, mission_name, mission_date, location) values (244, 'Bambusa Aurum', '7/15/2024', '78 Jackson Drive');
insert into Mission (mission_id, mission_name, mission_date, location) values (245, 'Pfizerpen', '4/1/2025', '6899 Moulton Lane');
insert into Mission (mission_id, mission_name, mission_date, location) values (246, 'METOPROLOL SUCCINATE', '12/15/2024', '2 Truax Way');
insert into Mission (mission_id, mission_name, mission_date, location) values (247, 'Amoxicillin', '10/7/2024', '88665 Scoville Hill');
insert into Mission (mission_id, mission_name, mission_date, location) values (248, 'SINUS PAIN AND CONGESTION', '8/29/2024', '53 Birchwood Park');
insert into Mission (mission_id, mission_name, mission_date, location) values (249, 'diltiazem hydrochloride', '4/24/2024', '59010 Maryland Circle');
insert into Mission (mission_id, mission_name, mission_date, location) values (250, 'Diazepam Intensol', '4/6/2025', '1965 Sutteridge Trail');
insert into Mission (mission_id, mission_name, mission_date, location) values (251, 'Meloxicam', '9/21/2024', '1 Arapahoe Terrace');
insert into Mission (mission_id, mission_name, mission_date, location) values (252, 'Simvastatin', '12/6/2024', '7 Park Meadow Road');
insert into Mission (mission_id, mission_name, mission_date, location) values (253, 'METAXALONE', '9/30/2024', '42 Pankratz Plaza');
insert into Mission (mission_id, mission_name, mission_date, location) values (254, 'Naproxen', '12/30/2024', '38062 Aberg Plaza');
insert into Mission (mission_id, mission_name, mission_date, location) values (255, 'allergy and cold relief', '5/27/2024', '5 Mockingbird Way');
insert into Mission (mission_id, mission_name, mission_date, location) values (256, 'Formucare Triple Antibiotic', '6/29/2024', '7 Waywood Lane');
insert into Mission (mission_id, mission_name, mission_date, location) values (257, 'Dolce and Gabbana The Lift Foundation Soft Tan 160', '4/19/2024', '7277 Florence Terrace');
insert into Mission (mission_id, mission_name, mission_date, location) values (258, 'Lamisil', '6/28/2024', '9 Rutledge Trail');
insert into Mission (mission_id, mission_name, mission_date, location) values (259, 'Magnesium Sulfate', '12/9/2024', '96339 Loeprich Junction');
insert into Mission (mission_id, mission_name, mission_date, location) values (260, 'Camilia', '7/23/2024', '44113 Prairieview Street');
insert into Mission (mission_id, mission_name, mission_date, location) values (261, 'PureForce', '3/29/2025', '873 Glacier Hill Place');
insert into Mission (mission_id, mission_name, mission_date, location) values (262, 'Amlodipine Besylate and Benazepril Hydrochloride', '8/2/2024', '09 Melby Circle');
insert into Mission (mission_id, mission_name, mission_date, location) values (263, 'CLARINS Extra-Comfort Broad Spectrum SPF 15 Sunscreen Tint 107', '6/1/2024', '01000 Anhalt Street');
insert into Mission (mission_id, mission_name, mission_date, location) values (264, 'SHISEIDO WHITE LUCENT BRIGHTENING SPOT-CONTROL FOUNDATION (REFILL)', '3/23/2025', '07 Monica Alley');
insert into Mission (mission_id, mission_name, mission_date, location) values (265, 'Leader Medicated Wipes', '4/25/2024', '25 Bluejay Way');
insert into Mission (mission_id, mission_name, mission_date, location) values (266, 'Entacapone', '8/26/2024', '6 Elmside Plaza');
insert into Mission (mission_id, mission_name, mission_date, location) values (267, 'DR.G WHITENING BOOSTER AMPLE', '11/27/2024', '95260 Shelley Trail');
insert into Mission (mission_id, mission_name, mission_date, location) values (268, 'Ultra-TechneKow', '8/8/2024', '5525 Elgar Road');
insert into Mission (mission_id, mission_name, mission_date, location) values (269, 'Nitrogen', '3/6/2025', '7363 Jana Avenue');
insert into Mission (mission_id, mission_name, mission_date, location) values (270, 'Econazole Nitrate', '10/12/2024', '4 Columbus Parkway');
insert into Mission (mission_id, mission_name, mission_date, location) values (271, 'Clearskin', '7/10/2024', '91 Ridgeview Way');
insert into Mission (mission_id, mission_name, mission_date, location) values (272, 'Plum', '6/2/2024', '8558 Eagle Crest Pass');
insert into Mission (mission_id, mission_name, mission_date, location) values (273, 'Pepper Tree Pollen', '2/28/2025', '7333 Ridgeway Pass');
insert into Mission (mission_id, mission_name, mission_date, location) values (274, 'Cyclosporine', '7/8/2024', '6 Harbort Road');
insert into Mission (mission_id, mission_name, mission_date, location) values (275, 'Non Aspirin', '12/19/2024', '467 Derek Point');
insert into Mission (mission_id, mission_name, mission_date, location) values (276, 'Omeprazole', '7/2/2024', '356 Monica Pass');
insert into Mission (mission_id, mission_name, mission_date, location) values (277, 'Carbinoxamine Maleate', '10/10/2024', '79837 Old Gate Trail');
insert into Mission (mission_id, mission_name, mission_date, location) values (278, 'Leader Childrens Ibuprofen', '4/8/2024', '4913 Tony Street');
insert into Mission (mission_id, mission_name, mission_date, location) values (279, 'Bluefish', '12/15/2024', '75476 Center Terrace');
insert into Mission (mission_id, mission_name, mission_date, location) values (280, 'Orphenadrine Citrate', '11/16/2024', '71 Norway Maple Plaza');
insert into Mission (mission_id, mission_name, mission_date, location) values (281, 'Combivent', '10/31/2024', '0905 Morrow Avenue');
insert into Mission (mission_id, mission_name, mission_date, location) values (282, 'ALOE ICE', '8/20/2024', '2663 Almo Junction');
insert into Mission (mission_id, mission_name, mission_date, location) values (283, 'antifungal', '4/13/2024', '099 Tennyson Pass');
insert into Mission (mission_id, mission_name, mission_date, location) values (284, 'Clearasil', '6/10/2024', '98 Grover Street');
insert into Mission (mission_id, mission_name, mission_date, location) values (285, 'Moisturizing Face Screen SPF 30', '5/30/2024', '6719 Hanover Street');
insert into Mission (mission_id, mission_name, mission_date, location) values (286, 'SHISEIDO RADIANT LIFTING FOUNDATION', '5/5/2024', '3115 Troy Avenue');
insert into Mission (mission_id, mission_name, mission_date, location) values (287, 'levofloxacin', '4/3/2025', '77 Service Plaza');
insert into Mission (mission_id, mission_name, mission_date, location) values (288, 'Promethazine VC', '5/13/2024', '2784 Warbler Avenue');
insert into Mission (mission_id, mission_name, mission_date, location) values (289, 'Tobramycin', '3/17/2025', '51732 Shelley Center');
insert into Mission (mission_id, mission_name, mission_date, location) values (290, 'Mepivacaine', '9/12/2024', '6909 Karstens Road');
insert into Mission (mission_id, mission_name, mission_date, location) values (291, 'Donepezil Hydrochloride', '5/21/2024', '0292 Springs Drive');
insert into Mission (mission_id, mission_name, mission_date, location) values (292, 'Elta MD UV Clear', '6/2/2024', '4 Pierstorff Place');
insert into Mission (mission_id, mission_name, mission_date, location) values (293, 'BOBBI BROWN BRIGHTENING PROTECTIVE FACE BASE', '3/28/2025', '07 Kennedy Street');
insert into Mission (mission_id, mission_name, mission_date, location) values (294, 'GOLDSHIELD 24', '1/13/2025', '05 Fairfield Street');
insert into Mission (mission_id, mission_name, mission_date, location) values (295, 'benzonatate', '5/25/2024', '63 Jana Avenue');
insert into Mission (mission_id, mission_name, mission_date, location) values (296, 'all day relief', '12/29/2024', '98 Jackson Crossing');
insert into Mission (mission_id, mission_name, mission_date, location) values (297, 'SEROQUEL', '5/26/2024', '427 Harper Street');
insert into Mission (mission_id, mission_name, mission_date, location) values (298, 'Ciprofloxacin', '5/19/2024', '09 Kennedy Terrace');
insert into Mission (mission_id, mission_name, mission_date, location) values (299, 'PVP Prep Pad', '3/11/2025', '79338 Cordelia Trail');
insert into Mission (mission_id, mission_name, mission_date, location) values (300, 'Wilate - von Willebrand Factor/Coagulation Factor VIII Complex (Human)', '12/2/2024', '62327 Artisan Circle');
insert into Mission (mission_id, mission_name, mission_date, location) values (301, 'ConZip', '7/15/2024', '73 International Point');
insert into Mission (mission_id, mission_name, mission_date, location) values (302, 'oxycodone hydrochloride', '5/22/2024', '4 Dahle Terrace');
insert into Mission (mission_id, mission_name, mission_date, location) values (303, 'Glipizide', '1/3/2025', '9189 Northport Street');
insert into Mission (mission_id, mission_name, mission_date, location) values (304, 'Glipizide', '3/3/2025', '619 Tony Parkway');
insert into Mission (mission_id, mission_name, mission_date, location) values (305, 'Topical 60 Sec Sodium Fluoride', '12/23/2024', '58 Caliangt Court');
insert into Mission (mission_id, mission_name, mission_date, location) values (306, 'Lescol', '6/9/2024', '959 Carberry Parkway');
insert into Mission (mission_id, mission_name, mission_date, location) values (307, 'Daily Defense', '1/21/2025', '45 Talisman Parkway');
insert into Mission (mission_id, mission_name, mission_date, location) values (308, 'Zep Professional Mild Antimicrobial Hand Cleaner', '6/13/2024', '6115 Logan Road');
insert into Mission (mission_id, mission_name, mission_date, location) values (309, 'Neomycin Polymyxin B Sulfates and Dexamethasone', '11/20/2024', '42 Sunnyside Street');
insert into Mission (mission_id, mission_name, mission_date, location) values (310, 'Soft Care Foam Select Antibacterial Triclosan', '11/24/2024', '3863 Nelson Lane');
insert into Mission (mission_id, mission_name, mission_date, location) values (311, 'LBEL COULEUR LUXE AMPLIFIER XP', '6/8/2024', '8 Straubel Parkway');
insert into Mission (mission_id, mission_name, mission_date, location) values (312, 'Cantharis 30c', '11/8/2024', '8 Summit Drive');
insert into Mission (mission_id, mission_name, mission_date, location) values (313, 'Valacyclovir Hydrochloride', '2/28/2025', '14542 Duke Center');
insert into Mission (mission_id, mission_name, mission_date, location) values (314, 'CHLORZOXAZONE', '10/9/2024', '28013 Toban Junction');
insert into Mission (mission_id, mission_name, mission_date, location) values (315, 'Vinceel', '5/21/2024', '12573 Mandrake Road');
insert into Mission (mission_id, mission_name, mission_date, location) values (316, 'Warfarin Sodium', '3/30/2025', '2733 Menomonie Plaza');
insert into Mission (mission_id, mission_name, mission_date, location) values (317, 'Goats Milk', '8/14/2024', '163 Lakewood Park');
insert into Mission (mission_id, mission_name, mission_date, location) values (318, 'Indomethacin', '1/1/2025', '91668 Atwood Junction');
insert into Mission (mission_id, mission_name, mission_date, location) values (319, 'COUMADIN', '6/6/2024', '27 Oak Valley Way');
insert into Mission (mission_id, mission_name, mission_date, location) values (320, 'Zap APF', '11/29/2024', '61071 Northport Court');
insert into Mission (mission_id, mission_name, mission_date, location) values (321, 'SHISEIDO ULTIMATE SUN PROTECTION PLUS', '5/9/2024', '7 Welch Road');
insert into Mission (mission_id, mission_name, mission_date, location) values (322, 'Lisinopril', '9/10/2024', '80 Almo Drive');
insert into Mission (mission_id, mission_name, mission_date, location) values (323, 'PM Acetaminophen', '9/12/2024', '70 Northport Court');
insert into Mission (mission_id, mission_name, mission_date, location) values (324, 'Prednisone', '3/27/2025', '2 Lawn Terrace');
insert into Mission (mission_id, mission_name, mission_date, location) values (325, 'Olanzapine', '12/14/2024', '250 Mitchell Circle');
insert into Mission (mission_id, mission_name, mission_date, location) values (326, 'Irbesartan', '9/8/2024', '7 Straubel Street');
insert into Mission (mission_id, mission_name, mission_date, location) values (327, 'Ranitidine', '6/5/2024', '49 Doe Crossing Avenue');
insert into Mission (mission_id, mission_name, mission_date, location) values (328, 'Neutrogena Shine Control Makeup', '4/18/2024', '70562 Northridge Alley');
insert into Mission (mission_id, mission_name, mission_date, location) values (329, 'Fluoxetine', '8/14/2024', '114 Waxwing Alley');
insert into Mission (mission_id, mission_name, mission_date, location) values (330, 'leader pain reliever', '12/12/2024', '97345 Alpine Center');
insert into Mission (mission_id, mission_name, mission_date, location) values (331, 'Botanics Daily Hand Therapy Sunscreen SPF 10', '9/20/2024', '8 Westerfield Street');
insert into Mission (mission_id, mission_name, mission_date, location) values (332, 'Divista', '11/24/2024', '9936 Eagle Crest Parkway');
insert into Mission (mission_id, mission_name, mission_date, location) values (333, 'Triamcinolone Acetonide', '10/9/2024', '0 Jay Center');
insert into Mission (mission_id, mission_name, mission_date, location) values (334, 'Canadian Blue Grass', '5/1/2024', '52 Leroy Street');
insert into Mission (mission_id, mission_name, mission_date, location) values (335, 'PCMX with Emollient', '9/29/2024', '8119 Westerfield Park');
insert into Mission (mission_id, mission_name, mission_date, location) values (336, 'Anti-Diarrheal', '5/14/2024', '7896 Warbler Park');
insert into Mission (mission_id, mission_name, mission_date, location) values (337, 'Diazepam', '4/18/2024', '24597 Susan Place');
insert into Mission (mission_id, mission_name, mission_date, location) values (338, 'koala pals', '7/5/2024', '10 Linden Place');
insert into Mission (mission_id, mission_name, mission_date, location) values (339, 'Hand Sanitizer', '10/22/2024', '22691 Longview Street');
insert into Mission (mission_id, mission_name, mission_date, location) values (340, 'Invirase', '7/31/2024', '934 Golf View Circle');
insert into Mission (mission_id, mission_name, mission_date, location) values (341, 'Epinastine HCl', '12/19/2024', '37 Bunker Hill Street');
insert into Mission (mission_id, mission_name, mission_date, location) values (342, 'Bambusa Aurum', '12/16/2024', '8 Pennsylvania Point');
insert into Mission (mission_id, mission_name, mission_date, location) values (343, 'Fosamax', '4/25/2024', '922 Sycamore Street');
insert into Mission (mission_id, mission_name, mission_date, location) values (344, 'Night Time', '12/3/2024', '86 Northport Place');
insert into Mission (mission_id, mission_name, mission_date, location) values (345, 'Zolpidem Tartrate', '11/17/2024', '72524 Green Ridge Place');
insert into Mission (mission_id, mission_name, mission_date, location) values (346, 'Gabapentin', '8/4/2024', '625 Mifflin Lane');
insert into Mission (mission_id, mission_name, mission_date, location) values (347, 'Brut Black Ice', '4/5/2025', '30875 Glendale Road');
insert into Mission (mission_id, mission_name, mission_date, location) values (348, 'Denavir', '2/16/2025', '251 Farmco Way');
insert into Mission (mission_id, mission_name, mission_date, location) values (349, 'Butalbital, Aspirin, and Caffeine', '2/12/2025', '4 Iowa Street');
insert into Mission (mission_id, mission_name, mission_date, location) values (350, 'Pain Relief', '5/11/2024', '388 Esker Place');
insert into Mission (mission_id, mission_name, mission_date, location) values (351, 'Ibuprofen', '5/23/2024', '1 Farwell Plaza');
insert into Mission (mission_id, mission_name, mission_date, location) values (352, 'Food - Plant Source, Apple Malus sp.', '10/21/2024', '4 Namekagon Terrace');
insert into Mission (mission_id, mission_name, mission_date, location) values (353, 'BICILLIN C-R 900/300', '8/29/2024', '45 Hoepker Circle');
insert into Mission (mission_id, mission_name, mission_date, location) values (354, 'Axe Sharp Focus Invisible Solid', '10/15/2024', '271 Maple Circle');
insert into Mission (mission_id, mission_name, mission_date, location) values (355, 'Isosorbide Sublingual', '3/28/2025', '462 Briar Crest Park');
insert into Mission (mission_id, mission_name, mission_date, location) values (356, 'Calcium Composition', '3/1/2025', '143 Novick Crossing');
insert into Mission (mission_id, mission_name, mission_date, location) values (357, 'Oxygen', '10/27/2024', '35 Bay Hill');
insert into Mission (mission_id, mission_name, mission_date, location) values (358, 'MYUNG HAN MI IN DO FOUNDATION', '10/6/2024', '442 Arrowood Parkway');
insert into Mission (mission_id, mission_name, mission_date, location) values (359, 'Chem - Tox', '4/4/2025', '6 Pepper Wood Trail');
insert into Mission (mission_id, mission_name, mission_date, location) values (360, 'Vyvanse', '9/10/2024', '8237 Utah Road');
insert into Mission (mission_id, mission_name, mission_date, location) values (361, 'Kiss Fungi-Gone', '2/2/2025', '83664 Northridge Junction');
insert into Mission (mission_id, mission_name, mission_date, location) values (362, 'Mixed Vespid hymenoptera venom Venomil Maintenance', '8/4/2024', '96452 Kropf Court');
insert into Mission (mission_id, mission_name, mission_date, location) values (363, 'Mint Sunscreen Lip Moisturizer', '9/8/2024', '3 Park Meadow Terrace');
insert into Mission (mission_id, mission_name, mission_date, location) values (364, 'Ropinirole', '4/30/2024', '11393 Prentice Place');
insert into Mission (mission_id, mission_name, mission_date, location) values (365, 'CENTER-AL - PHLEUM PRATENSE POLLEN', '3/22/2025', '6466 Southridge Junction');
insert into Mission (mission_id, mission_name, mission_date, location) values (366, 'Medique Mediproxen', '2/28/2025', '015 Milwaukee Drive');
insert into Mission (mission_id, mission_name, mission_date, location) values (367, 'Ziprasidone hydrochloride', '6/17/2024', '028 Brickson Park Hill');
insert into Mission (mission_id, mission_name, mission_date, location) values (368, 'Metformin Hydrochloride', '1/13/2025', '79151 Weeping Birch Place');
insert into Mission (mission_id, mission_name, mission_date, location) values (369, 'Prednisone', '7/19/2024', '88499 Pearson Plaza');
insert into Mission (mission_id, mission_name, mission_date, location) values (370, 'Methenamine Mandelate', '1/20/2025', '5 Dwight Lane');
insert into Mission (mission_id, mission_name, mission_date, location) values (371, 'Clonidine Hydrochloride', '2/2/2025', '6 Lakewood Circle');
insert into Mission (mission_id, mission_name, mission_date, location) values (372, 'Terazosin Hydrochloride Anhydrous', '9/21/2024', '91 Rutledge Point');
insert into Mission (mission_id, mission_name, mission_date, location) values (373, 'Theo-24', '12/19/2024', '5461 Sugar Crossing');
insert into Mission (mission_id, mission_name, mission_date, location) values (374, 'nighttime', '11/7/2024', '146 Northport Junction');
insert into Mission (mission_id, mission_name, mission_date, location) values (375, 'Ibuprofen', '3/24/2025', '08 Rigney Place');
insert into Mission (mission_id, mission_name, mission_date, location) values (376, 'Borrelia Remedy', '10/29/2024', '166 Sage Parkway');
insert into Mission (mission_id, mission_name, mission_date, location) values (377, 'Blackeye Pea', '4/11/2024', '058 Mayer Hill');
insert into Mission (mission_id, mission_name, mission_date, location) values (378, 'Harvest Grape Antibacterial Foaming Hand Wash', '2/6/2025', '51385 Huxley Avenue');
insert into Mission (mission_id, mission_name, mission_date, location) values (379, 'Nighttime Cold n Cough 4 Kids', '10/1/2024', '6 Buena Vista Pass');
insert into Mission (mission_id, mission_name, mission_date, location) values (380, 'Undecylenic Acid', '6/19/2024', '11 Sachs Alley');
insert into Mission (mission_id, mission_name, mission_date, location) values (381, 'Aricept', '3/15/2025', '51 Anderson Center');
insert into Mission (mission_id, mission_name, mission_date, location) values (382, 'ADRUCIL', '2/8/2025', '65 Veith Street');
insert into Mission (mission_id, mission_name, mission_date, location) values (383, 'Paroxetine', '1/11/2025', '76822 Graedel Crossing');
insert into Mission (mission_id, mission_name, mission_date, location) values (384, 'SIMPLY RIGHT', '6/4/2024', '731 Meadow Vale Pass');
insert into Mission (mission_id, mission_name, mission_date, location) values (385, 'Mucinex', '1/24/2025', '5 Merchant Road');
insert into Mission (mission_id, mission_name, mission_date, location) values (386, 'Ampicillin', '6/10/2024', '4 Eliot Circle');
insert into Mission (mission_id, mission_name, mission_date, location) values (387, 'Adrenal Energy', '2/1/2025', '061 Hazelcrest Point');
insert into Mission (mission_id, mission_name, mission_date, location) values (388, 'Utom 40', '1/12/2025', '051 Erie Drive');
insert into Mission (mission_id, mission_name, mission_date, location) values (389, 'Instant Hand Sanitizer', '10/2/2024', '5910 Quincy Park');
insert into Mission (mission_id, mission_name, mission_date, location) values (390, 'leader childrens pain and fever', '1/15/2025', '1 Golf Course Parkway');
insert into Mission (mission_id, mission_name, mission_date, location) values (391, 'Western Juniper', '5/23/2024', '0 Moland Parkway');
insert into Mission (mission_id, mission_name, mission_date, location) values (392, 'Allergy Severe', '9/18/2024', '90536 Bashford Lane');
insert into Mission (mission_id, mission_name, mission_date, location) values (393, 'CELEBREX', '3/26/2025', '67 Quincy Way');
insert into Mission (mission_id, mission_name, mission_date, location) values (394, 'Lexapro', '3/27/2025', '76 Monica Street');
insert into Mission (mission_id, mission_name, mission_date, location) values (395, 'Lidocaine Hydrochloride', '12/1/2024', '988 Forest Run Avenue');
insert into Mission (mission_id, mission_name, mission_date, location) values (396, 'Molds - Alternaria/Hormodendrum Mix', '4/3/2025', '503 Oak Valley Point');
insert into Mission (mission_id, mission_name, mission_date, location) values (397, 'Childrens Allergy Relief', '3/26/2025', '8975 Tomscot Park');
insert into Mission (mission_id, mission_name, mission_date, location) values (398, 'Olive-Viate', '4/27/2024', '87 Mcbride Junction');
insert into Mission (mission_id, mission_name, mission_date, location) values (399, 'Lactated Ringers and Dextrose', '1/7/2025', '02182 Rockefeller Hill');
insert into Mission (mission_id, mission_name, mission_date, location) values (400, 'Clarithromycin', '9/17/2024', '697 Mitchell Way');
insert into Mission (mission_id, mission_name, mission_date, location) values (401, 'Waterless Anti-Bacterial Hand Cleanser', '12/10/2024', '7502 Golf Course Crossing');
insert into Mission (mission_id, mission_name, mission_date, location) values (402, 'Cosedal Drops', '5/6/2024', '431 Walton Parkway');
insert into Mission (mission_id, mission_name, mission_date, location) values (403, 'Nite-Time', '6/11/2024', '70493 Lukken Hill');
insert into Mission (mission_id, mission_name, mission_date, location) values (404, 'TAGAMET', '8/15/2024', '588 Sloan Place');
insert into Mission (mission_id, mission_name, mission_date, location) values (405, 'Levaquin', '7/5/2024', '103 American Ash Terrace');
insert into Mission (mission_id, mission_name, mission_date, location) values (406, 'Paricalcitol', '2/2/2025', '2 Towne Center');
insert into Mission (mission_id, mission_name, mission_date, location) values (407, 'Walgreens Cool N Heat', '4/7/2024', '3 Dahle Road');
insert into Mission (mission_id, mission_name, mission_date, location) values (408, 'Sunmark Nicotine', '12/23/2024', '32 Magdeline Hill');
insert into Mission (mission_id, mission_name, mission_date, location) values (409, 'ACTIVE RESURGENCE EYE', '8/25/2024', '8271 Grover Center');
insert into Mission (mission_id, mission_name, mission_date, location) values (410, 'Visine A', '7/21/2024', '036 Fairfield Road');
insert into Mission (mission_id, mission_name, mission_date, location) values (411, 'Lidocaine Hydrochloride', '6/3/2024', '9521 Old Shore Lane');
insert into Mission (mission_id, mission_name, mission_date, location) values (412, 'Treatment Set TS349574', '7/20/2024', '4 Dwight Junction');
insert into Mission (mission_id, mission_name, mission_date, location) values (413, 'pharMAX fibro', '2/10/2025', '1 Judy Park');
insert into Mission (mission_id, mission_name, mission_date, location) values (414, 'Mustela', '3/1/2025', '3538 Clarendon Park');
insert into Mission (mission_id, mission_name, mission_date, location) values (415, 'SUGAR FREE LEMON MINT HERB THROAT DROPS', '6/1/2024', '41128 Randy Avenue');
insert into Mission (mission_id, mission_name, mission_date, location) values (416, 'Hydrochlorothiazide', '7/9/2024', '06090 Walton Center');
insert into Mission (mission_id, mission_name, mission_date, location) values (417, 'Esoterica', '12/9/2024', '64 Graedel Circle');
insert into Mission (mission_id, mission_name, mission_date, location) values (418, 'Night Time Cough', '11/14/2024', '1739 Miller Parkway');
insert into Mission (mission_id, mission_name, mission_date, location) values (419, 'Zithromax', '1/8/2025', '543 Esch Point');
insert into Mission (mission_id, mission_name, mission_date, location) values (420, 'Mefenamic Acid', '12/13/2024', '01133 Mallard Plaza');
insert into Mission (mission_id, mission_name, mission_date, location) values (421, 'Prochlorperazine Maleate', '9/22/2024', '2 Rutledge Terrace');
insert into Mission (mission_id, mission_name, mission_date, location) values (422, 'LUCENTIS', '8/15/2024', '57366 Hintze Lane');
insert into Mission (mission_id, mission_name, mission_date, location) values (423, 'Nitrogen', '9/20/2024', '960 Eagan Drive');
insert into Mission (mission_id, mission_name, mission_date, location) values (424, 'HYDROMORPHONE HYDROCHLORIDE', '8/17/2024', '1 Buena Vista Crossing');
insert into Mission (mission_id, mission_name, mission_date, location) values (425, 'Silk Antibacterial Foaming Hand Fresh Pear', '7/18/2024', '574 Nelson Junction');
insert into Mission (mission_id, mission_name, mission_date, location) values (426, 'Good Sense Mucus ER', '4/25/2024', '4 Northfield Center');
insert into Mission (mission_id, mission_name, mission_date, location) values (427, 'OXYGEN', '9/16/2024', '48 Ryan Center');
insert into Mission (mission_id, mission_name, mission_date, location) values (428, 'Tizanidine', '3/5/2025', '53879 Longview Center');
insert into Mission (mission_id, mission_name, mission_date, location) values (429, 'Montelukast Sodium', '8/10/2024', '5 Stang Avenue');
insert into Mission (mission_id, mission_name, mission_date, location) values (430, 'Regular Strength Enteric coated aspirin', '9/22/2024', '25 Scofield Lane');
insert into Mission (mission_id, mission_name, mission_date, location) values (431, 'NICORETTE', '3/5/2025', '1988 Stuart Alley');
insert into Mission (mission_id, mission_name, mission_date, location) values (432, 'Aspirin NSAID', '9/23/2024', '80 Maple Wood Court');
insert into Mission (mission_id, mission_name, mission_date, location) values (433, 'Benzonatate', '4/20/2024', '52 Meadow Valley Lane');
insert into Mission (mission_id, mission_name, mission_date, location) values (434, 'aspirin', '4/1/2025', '05952 Mccormick Lane');
insert into Mission (mission_id, mission_name, mission_date, location) values (435, 'Tree of Heaven', '8/31/2024', '4 Homewood Center');
insert into Mission (mission_id, mission_name, mission_date, location) values (436, 'Klor-Con M20', '4/22/2024', '639 Lighthouse Bay Alley');
insert into Mission (mission_id, mission_name, mission_date, location) values (437, 'SkinCeuticals Blemish Plus Age Defense Acne Treatment', '12/10/2024', '4 4th Road');
insert into Mission (mission_id, mission_name, mission_date, location) values (438, 'LISINOPRIL', '1/31/2025', '67009 Helena Junction');
insert into Mission (mission_id, mission_name, mission_date, location) values (439, 'Tineacide Physician Formula', '7/18/2024', '8 Merrick Hill');
insert into Mission (mission_id, mission_name, mission_date, location) values (440, 'PCXX ONE MINTE GEL CREME DE MENTHE', '12/26/2024', '40 Rieder Junction');
insert into Mission (mission_id, mission_name, mission_date, location) values (441, 'Dextroamphetamine saccharate, amphetamine aspartate monohydrate, dextroamphetamine sulfate and amphetamine sulfate', '5/30/2024', '8439 Meadow Valley Alley');
insert into Mission (mission_id, mission_name, mission_date, location) values (442, 'Penicilium chrysogenum', '2/21/2025', '74 Evergreen Park');
insert into Mission (mission_id, mission_name, mission_date, location) values (443, 'Stomachin Antacid', '7/27/2024', '9709 Old Gate Hill');
insert into Mission (mission_id, mission_name, mission_date, location) values (444, 'Trimethobenzamide Hydrochloride', '1/4/2025', '3 Cascade Alley');
insert into Mission (mission_id, mission_name, mission_date, location) values (445, 'LOSARTAN POTASSIUM AND HYDROCHLOROTHIAZIDE', '9/2/2024', '8048 Golf View Court');
insert into Mission (mission_id, mission_name, mission_date, location) values (446, 'Ketoprofen', '5/21/2024', '2320 Evergreen Lane');
insert into Mission (mission_id, mission_name, mission_date, location) values (447, 'Carvedilol', '6/23/2024', '7 Johnson Circle');
insert into Mission (mission_id, mission_name, mission_date, location) values (448, 'Prednisone', '7/10/2024', '5807 Forest Dale Park');
insert into Mission (mission_id, mission_name, mission_date, location) values (449, 'Zaroxolyn', '12/16/2024', '0288 Westport Way');
insert into Mission (mission_id, mission_name, mission_date, location) values (450, 'Childrens Ibuprofen', '12/21/2024', '51477 Marquette Trail');
insert into Mission (mission_id, mission_name, mission_date, location) values (451, 'ESSENTIAL SOLUTION VITA C MASK SHEET', '7/27/2024', '4349 Canary Plaza');
insert into Mission (mission_id, mission_name, mission_date, location) values (452, 'Haloperidol', '4/11/2024', '50702 Grasskamp Parkway');
insert into Mission (mission_id, mission_name, mission_date, location) values (453, 'Pleo Not', '11/23/2024', '33993 Hovde Pass');
insert into Mission (mission_id, mission_name, mission_date, location) values (454, 'Box Elder', '8/21/2024', '13367 Becker Center');
insert into Mission (mission_id, mission_name, mission_date, location) values (455, 'Aspirin', '1/13/2025', '20042 Mallard Parkway');
insert into Mission (mission_id, mission_name, mission_date, location) values (456, 'Childrens Wal Zyr 24 Hour Allergy', '6/14/2024', '50 Carey Court');
insert into Mission (mission_id, mission_name, mission_date, location) values (457, 'Cold and Cough', '12/25/2024', '8 Banding Plaza');
insert into Mission (mission_id, mission_name, mission_date, location) values (458, 'Metoprolol Tartrate', '2/1/2025', '22 Maywood Drive');
insert into Mission (mission_id, mission_name, mission_date, location) values (459, 'Aralast', '6/5/2024', '42 Springs Parkway');
insert into Mission (mission_id, mission_name, mission_date, location) values (460, 'all day allergy', '10/1/2024', '420 Merchant Way');
insert into Mission (mission_id, mission_name, mission_date, location) values (461, 'WellPatch Capsaicin Pain Relief', '9/13/2024', '418 Miller Hill');
insert into Mission (mission_id, mission_name, mission_date, location) values (462, 'Digoxin', '4/8/2024', '466 Riverside Circle');
insert into Mission (mission_id, mission_name, mission_date, location) values (463, 'Medique Guaicon DMS', '11/5/2024', '02 Loeprich Alley');
insert into Mission (mission_id, mission_name, mission_date, location) values (464, 'Skin Rash Acne', '2/11/2025', '61 Utah Place');
insert into Mission (mission_id, mission_name, mission_date, location) values (465, 'Topex', '1/5/2025', '3621 Barnett Circle');
insert into Mission (mission_id, mission_name, mission_date, location) values (466, 'Colgate Triple Action Original Mint Fluoride', '12/2/2024', '229 Sycamore Alley');
insert into Mission (mission_id, mission_name, mission_date, location) values (467, 'THE FLOWER UV INTENSE PACT', '3/6/2025', '95 Corben Pass');
insert into Mission (mission_id, mission_name, mission_date, location) values (468, 'Alprazolam', '8/5/2024', '99134 Orin Avenue');
insert into Mission (mission_id, mission_name, mission_date, location) values (469, 'Felodipine', '8/29/2024', '1 Stang Drive');
insert into Mission (mission_id, mission_name, mission_date, location) values (470, 'Loratadine', '5/19/2024', '27 Sauthoff Court');
insert into Mission (mission_id, mission_name, mission_date, location) values (471, 'Dental Plak', '5/22/2024', '466 Monterey Alley');
insert into Mission (mission_id, mission_name, mission_date, location) values (472, 'Eucalyptus', '7/24/2024', '30 Monterey Place');
insert into Mission (mission_id, mission_name, mission_date, location) values (473, 'mucus er', '4/18/2024', '9663 American Terrace');
insert into Mission (mission_id, mission_name, mission_date, location) values (474, 'Arnica Montana', '5/21/2024', '2 Troy Court');
insert into Mission (mission_id, mission_name, mission_date, location) values (475, 'Calloused', '5/7/2024', '28 Cambridge Lane');
insert into Mission (mission_id, mission_name, mission_date, location) values (476, 'CARBAMAZEPINE', '8/27/2024', '3 Merry Circle');
insert into Mission (mission_id, mission_name, mission_date, location) values (477, 'Bisoprolol Fumarate', '6/1/2024', '5497 Milwaukee Point');
insert into Mission (mission_id, mission_name, mission_date, location) values (478, 'CLARINS Broad Spectrum SPF 20 Super Restorative Tinted Tint 02', '12/21/2024', '30461 Schlimgen Pass');
insert into Mission (mission_id, mission_name, mission_date, location) values (479, 'health mart clearlax', '1/6/2025', '0 Goodland Center');
insert into Mission (mission_id, mission_name, mission_date, location) values (480, 'heartburn prevention', '3/18/2025', '6 Continental Pass');
insert into Mission (mission_id, mission_name, mission_date, location) values (481, 'DR RECKEWEG BC-1', '6/20/2024', '61665 Graceland Alley');
insert into Mission (mission_id, mission_name, mission_date, location) values (482, 'Warfarin Sodium', '3/17/2025', '7 Dunning Drive');
insert into Mission (mission_id, mission_name, mission_date, location) values (483, 'Ifosfamide and Mesna', '2/28/2025', '41 Service Terrace');
insert into Mission (mission_id, mission_name, mission_date, location) values (484, 'Chlorpheniramine Maleate', '12/1/2024', '6 Thierer Parkway');
insert into Mission (mission_id, mission_name, mission_date, location) values (485, 'Cephalexin', '10/11/2024', '6347 Donald Terrace');
insert into Mission (mission_id, mission_name, mission_date, location) values (486, 'Benzalkonium Chloride', '5/15/2024', '391 Muir Alley');
insert into Mission (mission_id, mission_name, mission_date, location) values (487, 'Tramadol Hydrochloride and Acetaminophen', '1/18/2025', '0564 Artisan Junction');
insert into Mission (mission_id, mission_name, mission_date, location) values (488, 'Lidocaine and Prilocaine', '1/15/2025', '80092 Dwight Point');
insert into Mission (mission_id, mission_name, mission_date, location) values (489, 'All Day Pain Relief', '8/29/2024', '2 Mallard Center');
insert into Mission (mission_id, mission_name, mission_date, location) values (490, 'SKIN CAVIAR CONCEALER FOUNDATION SUNSCREEN SPF 15 - Creme Blush', '5/12/2024', '32676 Oak Valley Point');
insert into Mission (mission_id, mission_name, mission_date, location) values (491, 'Citrus Basil Antibacterial Creamy Hand Wash', '4/10/2024', '40610 Algoma Road');
insert into Mission (mission_id, mission_name, mission_date, location) values (492, 'Phoma', '6/12/2024', '621 Welch Pass');
insert into Mission (mission_id, mission_name, mission_date, location) values (493, 'Zolpidem Tartrate', '6/30/2024', '4 Manley Court');
insert into Mission (mission_id, mission_name, mission_date, location) values (494, 'Dermarest', '6/12/2024', '34 Brickson Park Way');
insert into Mission (mission_id, mission_name, mission_date, location) values (495, 'FUROSEMIDE', '8/11/2024', '475 Warrior Court');
insert into Mission (mission_id, mission_name, mission_date, location) values (496, 'Xyzal', '5/27/2024', '4151 Starling Road');
insert into Mission (mission_id, mission_name, mission_date, location) values (497, 'Isosorbide Mononitrate', '4/21/2024', '783 Arkansas Road');
insert into Mission (mission_id, mission_name, mission_date, location) values (498, 'Clarithromycin', '11/17/2024', '8 Grayhawk Way');
insert into Mission (mission_id, mission_name, mission_date, location) values (499, 'Sunmark Nasal', '5/20/2024', '87 Thierer Drive');
insert into Mission (mission_id, mission_name, mission_date, location) values (500, 'Trezix', '10/18/2024', '9 Washington Court');
